//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/12/18 - 22:56:15
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="gerenciaresonanciasResult"/> and <see cref="gerenciaresonanciasResultDto"/>.
    /// </summary>
    public static partial class gerenciaresonanciasResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="gerenciaresonanciasResultDto"/> converted from <see cref="gerenciaresonanciasResult"/>.</param>
        static partial void OnDTO(this gerenciaresonanciasResult entity, gerenciaresonanciasResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="gerenciaresonanciasResult"/> converted from <see cref="gerenciaresonanciasResultDto"/>.</param>
        static partial void OnEntity(this gerenciaresonanciasResultDto dto, gerenciaresonanciasResult entity);

        /// <summary>
        /// Converts this instance of <see cref="gerenciaresonanciasResultDto"/> to an instance of <see cref="gerenciaresonanciasResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="gerenciaresonanciasResultDto"/> to convert.</param>
        public static gerenciaresonanciasResult ToEntity(this gerenciaresonanciasResultDto dto)
        {
            if (dto == null) return null;

            var entity = new gerenciaresonanciasResult();

            entity.Servicio = dto.Servicio;
            entity.Paciente = dto.Paciente;
            entity.F_Servicio = dto.F_Servicio;
            entity.Identificador = dto.Identificador;
            entity.Resonancia = dto.Resonancia;
            entity.F_Resonancia = dto.F_Resonancia;
            entity.Precio = dto.Precio;
            entity.Saldo_Paciente = dto.Saldo_Paciente;
            entity.SaldoAseguradora = dto.SaldoAseguradora;
            entity.Medico = dto.Medico;
            entity.Protocolo = dto.Protocolo;
            entity.Plan = dto.Plan;
            entity.Procedencia = dto.Procedencia;
            entity.Factor = dto.Factor;
            entity.Descuento_PPS = dto.Descuento_PPS;
            entity.Deducible = dto.Deducible;
            entity.Coaseguro = dto.Coaseguro;
            entity.Trabajador = dto.Trabajador;
            entity.Tipo = dto.Tipo;
            entity.Value1 = dto.Value1;
            entity.Value2 = dto.Value2;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="gerenciaresonanciasResult"/> to an instance of <see cref="gerenciaresonanciasResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="gerenciaresonanciasResult"/> to convert.</param>
        public static gerenciaresonanciasResultDto ToDTO(this gerenciaresonanciasResult entity)
        {
            if (entity == null) return null;

            var dto = new gerenciaresonanciasResultDto();

            dto.Servicio = entity.Servicio;
            dto.Paciente = entity.Paciente;
            dto.F_Servicio = entity.F_Servicio;
            dto.Identificador = entity.Identificador;
            dto.Resonancia = entity.Resonancia;
            dto.F_Resonancia = entity.F_Resonancia;
            dto.Precio = entity.Precio;
            dto.Saldo_Paciente = entity.Saldo_Paciente;
            dto.SaldoAseguradora = entity.SaldoAseguradora;
            dto.Medico = entity.Medico;
            dto.Protocolo = entity.Protocolo;
            dto.Plan = entity.Plan;
            dto.Procedencia = entity.Procedencia;
            dto.Factor = entity.Factor;
            dto.Descuento_PPS = entity.Descuento_PPS;
            dto.Deducible = entity.Deducible;
            dto.Coaseguro = entity.Coaseguro;
            dto.Trabajador = entity.Trabajador;
            dto.Tipo = entity.Tipo;
            dto.Value1 = entity.Value1;
            dto.Value2 = entity.Value2;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="gerenciaresonanciasResultDto"/> to an instance of <see cref="gerenciaresonanciasResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<gerenciaresonanciasResult> ToEntities(this IEnumerable<gerenciaresonanciasResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="gerenciaresonanciasResult"/> to an instance of <see cref="gerenciaresonanciasResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<gerenciaresonanciasResultDto> ToDTOs(this IEnumerable<gerenciaresonanciasResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
