//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/12/18 - 22:56:16
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="gerenciatipoexamen_asistencialResult"/> and <see cref="gerenciatipoexamen_asistencialResultDto"/>.
    /// </summary>
    public static partial class gerenciatipoexamen_asistencialResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="gerenciatipoexamen_asistencialResultDto"/> converted from <see cref="gerenciatipoexamen_asistencialResult"/>.</param>
        static partial void OnDTO(this gerenciatipoexamen_asistencialResult entity, gerenciatipoexamen_asistencialResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="gerenciatipoexamen_asistencialResult"/> converted from <see cref="gerenciatipoexamen_asistencialResultDto"/>.</param>
        static partial void OnEntity(this gerenciatipoexamen_asistencialResultDto dto, gerenciatipoexamen_asistencialResult entity);

        /// <summary>
        /// Converts this instance of <see cref="gerenciatipoexamen_asistencialResultDto"/> to an instance of <see cref="gerenciatipoexamen_asistencialResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="gerenciatipoexamen_asistencialResultDto"/> to convert.</param>
        public static gerenciatipoexamen_asistencialResult ToEntity(this gerenciatipoexamen_asistencialResultDto dto)
        {
            if (dto == null) return null;

            var entity = new gerenciatipoexamen_asistencialResult();

            entity.TipoEso = dto.TipoEso;
            entity.Empresa = dto.Empresa;
            entity.Trabajador = dto.Trabajador;
            entity.CostoExamen = dto.CostoExamen;
            entity.Comprobante = dto.Comprobante;
            entity.FechaFactura = dto.FechaFactura;
            entity.ServiceId = dto.ServiceId;
            entity.FechaServicio = dto.FechaServicio;
            entity.UsuarioAgenda = dto.UsuarioAgenda;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="gerenciatipoexamen_asistencialResult"/> to an instance of <see cref="gerenciatipoexamen_asistencialResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="gerenciatipoexamen_asistencialResult"/> to convert.</param>
        public static gerenciatipoexamen_asistencialResultDto ToDTO(this gerenciatipoexamen_asistencialResult entity)
        {
            if (entity == null) return null;

            var dto = new gerenciatipoexamen_asistencialResultDto();

            dto.TipoEso = entity.TipoEso;
            dto.Empresa = entity.Empresa;
            dto.Trabajador = entity.Trabajador;
            dto.CostoExamen = entity.CostoExamen;
            dto.Comprobante = entity.Comprobante;
            dto.FechaFactura = entity.FechaFactura;
            dto.ServiceId = entity.ServiceId;
            dto.FechaServicio = entity.FechaServicio;
            dto.UsuarioAgenda = entity.UsuarioAgenda;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="gerenciatipoexamen_asistencialResultDto"/> to an instance of <see cref="gerenciatipoexamen_asistencialResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<gerenciatipoexamen_asistencialResult> ToEntities(this IEnumerable<gerenciatipoexamen_asistencialResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="gerenciatipoexamen_asistencialResult"/> to an instance of <see cref="gerenciatipoexamen_asistencialResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<gerenciatipoexamen_asistencialResultDto> ToDTOs(this IEnumerable<gerenciatipoexamen_asistencialResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
