//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:31:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="concatenaterecomendacionesbycategoria_spResult"/> and <see cref="concatenaterecomendacionesbycategoria_spResultDto"/>.
    /// </summary>
    public static partial class concatenaterecomendacionesbycategoria_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="concatenaterecomendacionesbycategoria_spResultDto"/> converted from <see cref="concatenaterecomendacionesbycategoria_spResult"/>.</param>
        static partial void OnDTO(this concatenaterecomendacionesbycategoria_spResult entity, concatenaterecomendacionesbycategoria_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="concatenaterecomendacionesbycategoria_spResult"/> converted from <see cref="concatenaterecomendacionesbycategoria_spResultDto"/>.</param>
        static partial void OnEntity(this concatenaterecomendacionesbycategoria_spResultDto dto, concatenaterecomendacionesbycategoria_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="concatenaterecomendacionesbycategoria_spResultDto"/> to an instance of <see cref="concatenaterecomendacionesbycategoria_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="concatenaterecomendacionesbycategoria_spResultDto"/> to convert.</param>
        public static concatenaterecomendacionesbycategoria_spResult ToEntity(this concatenaterecomendacionesbycategoria_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new concatenaterecomendacionesbycategoria_spResult();

            entity.v_RestrictionsName = dto.v_RestrictionsName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="concatenaterecomendacionesbycategoria_spResult"/> to an instance of <see cref="concatenaterecomendacionesbycategoria_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="concatenaterecomendacionesbycategoria_spResult"/> to convert.</param>
        public static concatenaterecomendacionesbycategoria_spResultDto ToDTO(this concatenaterecomendacionesbycategoria_spResult entity)
        {
            if (entity == null) return null;

            var dto = new concatenaterecomendacionesbycategoria_spResultDto();

            dto.v_RestrictionsName = entity.v_RestrictionsName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="concatenaterecomendacionesbycategoria_spResultDto"/> to an instance of <see cref="concatenaterecomendacionesbycategoria_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<concatenaterecomendacionesbycategoria_spResult> ToEntities(this IEnumerable<concatenaterecomendacionesbycategoria_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="concatenaterecomendacionesbycategoria_spResult"/> to an instance of <see cref="concatenaterecomendacionesbycategoria_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<concatenaterecomendacionesbycategoria_spResultDto> ToDTOs(this IEnumerable<concatenaterecomendacionesbycategoria_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
