//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:37:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="cotizacionoc"/> and <see cref="cotizacionocDto"/>.
    /// </summary>
    public static partial class cotizacionocAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="cotizacionocDto"/> converted from <see cref="cotizacionoc"/>.</param>
        static partial void OnDTO(this cotizacionoc entity, cotizacionocDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="cotizacionoc"/> converted from <see cref="cotizacionocDto"/>.</param>
        static partial void OnEntity(this cotizacionocDto dto, cotizacionoc entity);

        /// <summary>
        /// Converts this instance of <see cref="cotizacionocDto"/> to an instance of <see cref="cotizacionoc"/>.
        /// </summary>
        /// <param name="dto"><see cref="cotizacionocDto"/> to convert.</param>
        public static cotizacionoc ToEntity(this cotizacionocDto dto)
        {
            if (dto == null) return null;

            var entity = new cotizacionoc();

            entity.i_CotizacionIdOc = dto.i_CotizacionIdOc;
            entity.i_EmpresaId = dto.i_EmpresaId;
            entity.i_PersonId = dto.i_PersonId;
            entity.v_Description = dto.v_Description;
            entity.v_Comentary = dto.v_Comentary;
            entity.i_NumberOfWorker = dto.i_NumberOfWorker;
            entity.r_TotalCost = dto.r_TotalCost;
            entity.d_DeliveryDate = dto.d_DeliveryDate;
            entity.i_LineaCreditoId = dto.i_LineaCreditoId;
            entity.i_EMOType = dto.i_EMOType;
            entity.i_InsertUserId = dto.i_InsertUserId;
            entity.d_InsertDate = dto.d_InsertDate;
            entity.i_UpdateUserId = dto.i_UpdateUserId;
            entity.d_UpdateDate = dto.d_UpdateDate;
            entity.v_ComentaryUpdate = dto.v_ComentaryUpdate;
            entity.i_MostrarPrecio = dto.i_MostrarPrecio;
            entity.v_RazonSocial = dto.v_RazonSocial;
            entity.v_RepresentanteLegal = dto.v_RepresentanteLegal;
            entity.v_DireccionEmpresa = dto.v_DireccionEmpresa;
            entity.v_Sumilla = dto.v_Sumilla;
            entity.v_Asunto = dto.v_Asunto;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.v_Interconsultas = dto.v_Interconsultas;
            entity.v_Anotaciones = dto.v_Anotaciones;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="cotizacionoc"/> to an instance of <see cref="cotizacionocDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="cotizacionoc"/> to convert.</param>
        public static cotizacionocDto ToDTO(this cotizacionoc entity)
        {
            if (entity == null) return null;

            var dto = new cotizacionocDto();

            dto.i_CotizacionIdOc = entity.i_CotizacionIdOc;
            dto.i_EmpresaId = entity.i_EmpresaId;
            dto.i_PersonId = entity.i_PersonId;
            dto.v_Description = entity.v_Description;
            dto.v_Comentary = entity.v_Comentary;
            dto.i_NumberOfWorker = entity.i_NumberOfWorker;
            dto.r_TotalCost = entity.r_TotalCost;
            dto.d_DeliveryDate = entity.d_DeliveryDate;
            dto.i_LineaCreditoId = entity.i_LineaCreditoId;
            dto.i_EMOType = entity.i_EMOType;
            dto.i_InsertUserId = entity.i_InsertUserId;
            dto.d_InsertDate = entity.d_InsertDate;
            dto.i_UpdateUserId = entity.i_UpdateUserId;
            dto.d_UpdateDate = entity.d_UpdateDate;
            dto.v_ComentaryUpdate = entity.v_ComentaryUpdate;
            dto.i_MostrarPrecio = entity.i_MostrarPrecio;
            dto.v_RazonSocial = entity.v_RazonSocial;
            dto.v_RepresentanteLegal = entity.v_RepresentanteLegal;
            dto.v_DireccionEmpresa = entity.v_DireccionEmpresa;
            dto.v_Sumilla = entity.v_Sumilla;
            dto.v_Asunto = entity.v_Asunto;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.v_Interconsultas = entity.v_Interconsultas;
            dto.v_Anotaciones = entity.v_Anotaciones;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="cotizacionocDto"/> to an instance of <see cref="cotizacionoc"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<cotizacionoc> ToEntities(this IEnumerable<cotizacionocDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="cotizacionoc"/> to an instance of <see cref="cotizacionocDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<cotizacionocDto> ToDTOs(this IEnumerable<cotizacionoc> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
