//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:31:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="devolvercomponentesconcatenados_spResult"/> and <see cref="devolvercomponentesconcatenados_spResultDto"/>.
    /// </summary>
    public static partial class devolvercomponentesconcatenados_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="devolvercomponentesconcatenados_spResultDto"/> converted from <see cref="devolvercomponentesconcatenados_spResult"/>.</param>
        static partial void OnDTO(this devolvercomponentesconcatenados_spResult entity, devolvercomponentesconcatenados_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="devolvercomponentesconcatenados_spResult"/> converted from <see cref="devolvercomponentesconcatenados_spResultDto"/>.</param>
        static partial void OnEntity(this devolvercomponentesconcatenados_spResultDto dto, devolvercomponentesconcatenados_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="devolvercomponentesconcatenados_spResultDto"/> to an instance of <see cref="devolvercomponentesconcatenados_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="devolvercomponentesconcatenados_spResultDto"/> to convert.</param>
        public static devolvercomponentesconcatenados_spResult ToEntity(this devolvercomponentesconcatenados_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new devolvercomponentesconcatenados_spResult();

            entity.NombreComponente = dto.NombreComponente;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="devolvercomponentesconcatenados_spResult"/> to an instance of <see cref="devolvercomponentesconcatenados_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="devolvercomponentesconcatenados_spResult"/> to convert.</param>
        public static devolvercomponentesconcatenados_spResultDto ToDTO(this devolvercomponentesconcatenados_spResult entity)
        {
            if (entity == null) return null;

            var dto = new devolvercomponentesconcatenados_spResultDto();

            dto.NombreComponente = entity.NombreComponente;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="devolvercomponentesconcatenados_spResultDto"/> to an instance of <see cref="devolvercomponentesconcatenados_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<devolvercomponentesconcatenados_spResult> ToEntities(this IEnumerable<devolvercomponentesconcatenados_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="devolvercomponentesconcatenados_spResult"/> to an instance of <see cref="devolvercomponentesconcatenados_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<devolvercomponentesconcatenados_spResultDto> ToDTOs(this IEnumerable<devolvercomponentesconcatenados_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
