//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:31:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="devolverhabitos_personales_listamedicospersonales_spResult"/> and <see cref="devolverhabitos_personales_listamedicospersonales_spResultDto"/>.
    /// </summary>
    public static partial class devolverhabitos_personales_listamedicospersonales_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="devolverhabitos_personales_listamedicospersonales_spResultDto"/> converted from <see cref="devolverhabitos_personales_listamedicospersonales_spResult"/>.</param>
        static partial void OnDTO(this devolverhabitos_personales_listamedicospersonales_spResult entity, devolverhabitos_personales_listamedicospersonales_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="devolverhabitos_personales_listamedicospersonales_spResult"/> converted from <see cref="devolverhabitos_personales_listamedicospersonales_spResultDto"/>.</param>
        static partial void OnEntity(this devolverhabitos_personales_listamedicospersonales_spResultDto dto, devolverhabitos_personales_listamedicospersonales_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="devolverhabitos_personales_listamedicospersonales_spResultDto"/> to an instance of <see cref="devolverhabitos_personales_listamedicospersonales_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="devolverhabitos_personales_listamedicospersonales_spResultDto"/> to convert.</param>
        public static devolverhabitos_personales_listamedicospersonales_spResult ToEntity(this devolverhabitos_personales_listamedicospersonales_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new devolverhabitos_personales_listamedicospersonales_spResult();

            entity.v_PersonId = dto.v_PersonId;
            entity.v_DiseasesId = dto.v_DiseasesId;
            entity.v_DiseasesName = dto.v_DiseasesName;
            entity.i_Answer = dto.i_Answer;
            entity.v_GroupName = dto.v_GroupName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="devolverhabitos_personales_listamedicospersonales_spResult"/> to an instance of <see cref="devolverhabitos_personales_listamedicospersonales_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="devolverhabitos_personales_listamedicospersonales_spResult"/> to convert.</param>
        public static devolverhabitos_personales_listamedicospersonales_spResultDto ToDTO(this devolverhabitos_personales_listamedicospersonales_spResult entity)
        {
            if (entity == null) return null;

            var dto = new devolverhabitos_personales_listamedicospersonales_spResultDto();

            dto.v_PersonId = entity.v_PersonId;
            dto.v_DiseasesId = entity.v_DiseasesId;
            dto.v_DiseasesName = entity.v_DiseasesName;
            dto.i_Answer = entity.i_Answer;
            dto.v_GroupName = entity.v_GroupName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="devolverhabitos_personales_listamedicospersonales_spResultDto"/> to an instance of <see cref="devolverhabitos_personales_listamedicospersonales_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<devolverhabitos_personales_listamedicospersonales_spResult> ToEntities(this IEnumerable<devolverhabitos_personales_listamedicospersonales_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="devolverhabitos_personales_listamedicospersonales_spResult"/> to an instance of <see cref="devolverhabitos_personales_listamedicospersonales_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<devolverhabitos_personales_listamedicospersonales_spResultDto> ToDTOs(this IEnumerable<devolverhabitos_personales_listamedicospersonales_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
