//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:31:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="devolvervalorcampoporserviciomejorado_spResult"/> and <see cref="devolvervalorcampoporserviciomejorado_spResultDto"/>.
    /// </summary>
    public static partial class devolvervalorcampoporserviciomejorado_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="devolvervalorcampoporserviciomejorado_spResultDto"/> converted from <see cref="devolvervalorcampoporserviciomejorado_spResult"/>.</param>
        static partial void OnDTO(this devolvervalorcampoporserviciomejorado_spResult entity, devolvervalorcampoporserviciomejorado_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="devolvervalorcampoporserviciomejorado_spResult"/> converted from <see cref="devolvervalorcampoporserviciomejorado_spResultDto"/>.</param>
        static partial void OnEntity(this devolvervalorcampoporserviciomejorado_spResultDto dto, devolvervalorcampoporserviciomejorado_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="devolvervalorcampoporserviciomejorado_spResultDto"/> to an instance of <see cref="devolvervalorcampoporserviciomejorado_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="devolvervalorcampoporserviciomejorado_spResultDto"/> to convert.</param>
        public static devolvervalorcampoporserviciomejorado_spResult ToEntity(this devolvervalorcampoporserviciomejorado_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new devolvervalorcampoporserviciomejorado_spResult();

            entity.ServicioId = dto.ServicioId;
            entity.Valor = dto.Valor;
            entity.NombreComponente = dto.NombreComponente;
            entity.IdComponente = dto.IdComponente;
            entity.NombreCampo = dto.NombreCampo;
            entity.IdCampo = dto.IdCampo;
            entity.i_GroupId = dto.i_GroupId;
            entity.ValorName = dto.ValorName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="devolvervalorcampoporserviciomejorado_spResult"/> to an instance of <see cref="devolvervalorcampoporserviciomejorado_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="devolvervalorcampoporserviciomejorado_spResult"/> to convert.</param>
        public static devolvervalorcampoporserviciomejorado_spResultDto ToDTO(this devolvervalorcampoporserviciomejorado_spResult entity)
        {
            if (entity == null) return null;

            var dto = new devolvervalorcampoporserviciomejorado_spResultDto();

            dto.ServicioId = entity.ServicioId;
            dto.Valor = entity.Valor;
            dto.NombreComponente = entity.NombreComponente;
            dto.IdComponente = entity.IdComponente;
            dto.NombreCampo = entity.NombreCampo;
            dto.IdCampo = entity.IdCampo;
            dto.i_GroupId = entity.i_GroupId;
            dto.ValorName = entity.ValorName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="devolvervalorcampoporserviciomejorado_spResultDto"/> to an instance of <see cref="devolvervalorcampoporserviciomejorado_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<devolvervalorcampoporserviciomejorado_spResult> ToEntities(this IEnumerable<devolvervalorcampoporserviciomejorado_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="devolvervalorcampoporserviciomejorado_spResult"/> to an instance of <see cref="devolvervalorcampoporserviciomejorado_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<devolvervalorcampoporserviciomejorado_spResultDto> ToDTOs(this IEnumerable<devolvervalorcampoporserviciomejorado_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
