//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:31:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="examenbydefaultorassigned_comfields_spResult"/> and <see cref="examenbydefaultorassigned_comfields_spResultDto"/>.
    /// </summary>
    public static partial class examenbydefaultorassigned_comfields_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="examenbydefaultorassigned_comfields_spResultDto"/> converted from <see cref="examenbydefaultorassigned_comfields_spResult"/>.</param>
        static partial void OnDTO(this examenbydefaultorassigned_comfields_spResult entity, examenbydefaultorassigned_comfields_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="examenbydefaultorassigned_comfields_spResult"/> converted from <see cref="examenbydefaultorassigned_comfields_spResultDto"/>.</param>
        static partial void OnEntity(this examenbydefaultorassigned_comfields_spResultDto dto, examenbydefaultorassigned_comfields_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="examenbydefaultorassigned_comfields_spResultDto"/> to an instance of <see cref="examenbydefaultorassigned_comfields_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="examenbydefaultorassigned_comfields_spResultDto"/> to convert.</param>
        public static examenbydefaultorassigned_comfields_spResult ToEntity(this examenbydefaultorassigned_comfields_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new examenbydefaultorassigned_comfields_spResult();

            entity.v_ComponentFieldId = dto.v_ComponentFieldId;
            entity.v_TextLabel = dto.v_TextLabel;
            entity.v_ComponentId = dto.v_ComponentId;
            entity.i_LabelWidth = dto.i_LabelWidth;
            entity.v_DefaultText = dto.v_DefaultText;
            entity.i_ControlId = dto.i_ControlId;
            entity.i_GroupId = dto.i_GroupId;
            entity.i_ItemId = dto.i_ItemId;
            entity.i_ControlWidth = dto.i_ControlWidth;
            entity.i_HeightControl = dto.i_HeightControl;
            entity.i_MaxLenght = dto.i_MaxLenght;
            entity.i_IsRequired = dto.i_IsRequired;
            entity.i_Column = dto.i_Column;
            entity.v_MeasurementUnitName = dto.v_MeasurementUnitName;
            entity.i_IsCalculate = dto.i_IsCalculate;
            entity.i_Order = dto.i_Order;
            entity.i_MeasurementUnitId = dto.i_MeasurementUnitId;
            entity.r_ValidateValue1 = dto.r_ValidateValue1;
            entity.r_ValidateValue2 = dto.r_ValidateValue2;
            entity.v_Group = dto.v_Group;
            entity.v_Formula = dto.v_Formula;
            entity.i_NroDecimales = dto.i_NroDecimales;
            entity.i_ReadOnly = dto.i_ReadOnly;
            entity.i_Enabled = dto.i_Enabled;
            entity.i_HasAutomaticDxId = dto.i_HasAutomaticDxId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="examenbydefaultorassigned_comfields_spResult"/> to an instance of <see cref="examenbydefaultorassigned_comfields_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="examenbydefaultorassigned_comfields_spResult"/> to convert.</param>
        public static examenbydefaultorassigned_comfields_spResultDto ToDTO(this examenbydefaultorassigned_comfields_spResult entity)
        {
            if (entity == null) return null;

            var dto = new examenbydefaultorassigned_comfields_spResultDto();

            dto.v_ComponentFieldId = entity.v_ComponentFieldId;
            dto.v_TextLabel = entity.v_TextLabel;
            dto.v_ComponentId = entity.v_ComponentId;
            dto.i_LabelWidth = entity.i_LabelWidth;
            dto.v_DefaultText = entity.v_DefaultText;
            dto.i_ControlId = entity.i_ControlId;
            dto.i_GroupId = entity.i_GroupId;
            dto.i_ItemId = entity.i_ItemId;
            dto.i_ControlWidth = entity.i_ControlWidth;
            dto.i_HeightControl = entity.i_HeightControl;
            dto.i_MaxLenght = entity.i_MaxLenght;
            dto.i_IsRequired = entity.i_IsRequired;
            dto.i_Column = entity.i_Column;
            dto.v_MeasurementUnitName = entity.v_MeasurementUnitName;
            dto.i_IsCalculate = entity.i_IsCalculate;
            dto.i_Order = entity.i_Order;
            dto.i_MeasurementUnitId = entity.i_MeasurementUnitId;
            dto.r_ValidateValue1 = entity.r_ValidateValue1;
            dto.r_ValidateValue2 = entity.r_ValidateValue2;
            dto.v_Group = entity.v_Group;
            dto.v_Formula = entity.v_Formula;
            dto.i_NroDecimales = entity.i_NroDecimales;
            dto.i_ReadOnly = entity.i_ReadOnly;
            dto.i_Enabled = entity.i_Enabled;
            dto.i_HasAutomaticDxId = entity.i_HasAutomaticDxId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="examenbydefaultorassigned_comfields_spResultDto"/> to an instance of <see cref="examenbydefaultorassigned_comfields_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<examenbydefaultorassigned_comfields_spResult> ToEntities(this IEnumerable<examenbydefaultorassigned_comfields_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="examenbydefaultorassigned_comfields_spResult"/> to an instance of <see cref="examenbydefaultorassigned_comfields_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<examenbydefaultorassigned_comfields_spResultDto> ToDTOs(this IEnumerable<examenbydefaultorassigned_comfields_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
