//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:31:52
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="gerenciafarmaciaasistencialResult"/> and <see cref="gerenciafarmaciaasistencialResultDto"/>.
    /// </summary>
    public static partial class gerenciafarmaciaasistencialResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="gerenciafarmaciaasistencialResultDto"/> converted from <see cref="gerenciafarmaciaasistencialResult"/>.</param>
        static partial void OnDTO(this gerenciafarmaciaasistencialResult entity, gerenciafarmaciaasistencialResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="gerenciafarmaciaasistencialResult"/> converted from <see cref="gerenciafarmaciaasistencialResultDto"/>.</param>
        static partial void OnEntity(this gerenciafarmaciaasistencialResultDto dto, gerenciafarmaciaasistencialResult entity);

        /// <summary>
        /// Converts this instance of <see cref="gerenciafarmaciaasistencialResultDto"/> to an instance of <see cref="gerenciafarmaciaasistencialResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="gerenciafarmaciaasistencialResultDto"/> to convert.</param>
        public static gerenciafarmaciaasistencialResult ToEntity(this gerenciafarmaciaasistencialResultDto dto)
        {
            if (dto == null) return null;

            var entity = new gerenciafarmaciaasistencialResult();

            entity.Servicio = dto.Servicio;
            entity.Medicina = dto.Medicina;
            entity.Cantidad = dto.Cantidad;
            entity.SubTotal = dto.SubTotal;
            entity.Igv = dto.Igv;
            entity.Total = dto.Total;
            entity.Comision = dto.Comision;
            entity.Medico = dto.Medico;
            entity.Protocolo = dto.Protocolo;
            entity.Trabajador = dto.Trabajador;
            entity.Paciente = dto.Paciente;
            entity.Fecha = dto.Fecha;
            entity.Value1 = dto.Value1;
            entity.Value2 = dto.Value2;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="gerenciafarmaciaasistencialResult"/> to an instance of <see cref="gerenciafarmaciaasistencialResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="gerenciafarmaciaasistencialResult"/> to convert.</param>
        public static gerenciafarmaciaasistencialResultDto ToDTO(this gerenciafarmaciaasistencialResult entity)
        {
            if (entity == null) return null;

            var dto = new gerenciafarmaciaasistencialResultDto();

            dto.Servicio = entity.Servicio;
            dto.Medicina = entity.Medicina;
            dto.Cantidad = entity.Cantidad;
            dto.SubTotal = entity.SubTotal;
            dto.Igv = entity.Igv;
            dto.Total = entity.Total;
            dto.Comision = entity.Comision;
            dto.Medico = entity.Medico;
            dto.Protocolo = entity.Protocolo;
            dto.Trabajador = entity.Trabajador;
            dto.Paciente = entity.Paciente;
            dto.Fecha = entity.Fecha;
            dto.Value1 = entity.Value1;
            dto.Value2 = entity.Value2;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="gerenciafarmaciaasistencialResultDto"/> to an instance of <see cref="gerenciafarmaciaasistencialResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<gerenciafarmaciaasistencialResult> ToEntities(this IEnumerable<gerenciafarmaciaasistencialResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="gerenciafarmaciaasistencialResult"/> to an instance of <see cref="gerenciafarmaciaasistencialResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<gerenciafarmaciaasistencialResultDto> ToDTOs(this IEnumerable<gerenciafarmaciaasistencialResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
