//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:31:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="gerenciatipoprotocoloResult"/> and <see cref="gerenciatipoprotocoloResultDto"/>.
    /// </summary>
    public static partial class gerenciatipoprotocoloResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="gerenciatipoprotocoloResultDto"/> converted from <see cref="gerenciatipoprotocoloResult"/>.</param>
        static partial void OnDTO(this gerenciatipoprotocoloResult entity, gerenciatipoprotocoloResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="gerenciatipoprotocoloResult"/> converted from <see cref="gerenciatipoprotocoloResultDto"/>.</param>
        static partial void OnEntity(this gerenciatipoprotocoloResultDto dto, gerenciatipoprotocoloResult entity);

        /// <summary>
        /// Converts this instance of <see cref="gerenciatipoprotocoloResultDto"/> to an instance of <see cref="gerenciatipoprotocoloResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="gerenciatipoprotocoloResultDto"/> to convert.</param>
        public static gerenciatipoprotocoloResult ToEntity(this gerenciatipoprotocoloResultDto dto)
        {
            if (dto == null) return null;

            var entity = new gerenciatipoprotocoloResult();

            entity.Servicio = dto.Servicio;
            entity.Paciente = dto.Paciente;
            entity.Protocolo = dto.Protocolo;
            entity.Fecha = dto.Fecha;
            entity.Trabajador = dto.Trabajador;
            entity.SRV = dto.SRV;
            entity.ProduccionServices = dto.ProduccionServices;
            entity.ProduccionHospi = dto.ProduccionHospi;
            entity.DOC = dto.DOC;
            entity.Total = dto.Total;
            entity.Saldo = dto.Saldo;
            entity.F_Comprobante = dto.F_Comprobante;
            entity.Condicion = dto.Condicion;
            entity.Tipo = dto.Tipo;
            entity.Medico = dto.Medico;
            entity.Procedencia = dto.Procedencia;
            entity.Value1 = dto.Value1;
            entity.Value2 = dto.Value2;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="gerenciatipoprotocoloResult"/> to an instance of <see cref="gerenciatipoprotocoloResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="gerenciatipoprotocoloResult"/> to convert.</param>
        public static gerenciatipoprotocoloResultDto ToDTO(this gerenciatipoprotocoloResult entity)
        {
            if (entity == null) return null;

            var dto = new gerenciatipoprotocoloResultDto();

            dto.Servicio = entity.Servicio;
            dto.Paciente = entity.Paciente;
            dto.Protocolo = entity.Protocolo;
            dto.Fecha = entity.Fecha;
            dto.Trabajador = entity.Trabajador;
            dto.SRV = entity.SRV;
            dto.ProduccionServices = entity.ProduccionServices;
            dto.ProduccionHospi = entity.ProduccionHospi;
            dto.DOC = entity.DOC;
            dto.Total = entity.Total;
            dto.Saldo = entity.Saldo;
            dto.F_Comprobante = entity.F_Comprobante;
            dto.Condicion = entity.Condicion;
            dto.Tipo = entity.Tipo;
            dto.Medico = entity.Medico;
            dto.Procedencia = entity.Procedencia;
            dto.Value1 = entity.Value1;
            dto.Value2 = entity.Value2;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="gerenciatipoprotocoloResultDto"/> to an instance of <see cref="gerenciatipoprotocoloResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<gerenciatipoprotocoloResult> ToEntities(this IEnumerable<gerenciatipoprotocoloResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="gerenciatipoprotocoloResult"/> to an instance of <see cref="gerenciatipoprotocoloResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<gerenciatipoprotocoloResultDto> ToDTOs(this IEnumerable<gerenciatipoprotocoloResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
