//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getantecedentconsolidateforservice2_spResult"/> and <see cref="getantecedentconsolidateforservice2_spResultDto"/>.
    /// </summary>
    public static partial class getantecedentconsolidateforservice2_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getantecedentconsolidateforservice2_spResultDto"/> converted from <see cref="getantecedentconsolidateforservice2_spResult"/>.</param>
        static partial void OnDTO(this getantecedentconsolidateforservice2_spResult entity, getantecedentconsolidateforservice2_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getantecedentconsolidateforservice2_spResult"/> converted from <see cref="getantecedentconsolidateforservice2_spResultDto"/>.</param>
        static partial void OnEntity(this getantecedentconsolidateforservice2_spResultDto dto, getantecedentconsolidateforservice2_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getantecedentconsolidateforservice2_spResultDto"/> to an instance of <see cref="getantecedentconsolidateforservice2_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getantecedentconsolidateforservice2_spResultDto"/> to convert.</param>
        public static getantecedentconsolidateforservice2_spResult ToEntity(this getantecedentconsolidateforservice2_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getantecedentconsolidateforservice2_spResult();

            entity.v_AntecedentTypeName = dto.v_AntecedentTypeName;
            entity.v_DiseasesId = dto.v_DiseasesId;
            entity.v_CIE10Id = dto.v_CIE10Id;
            entity.v_DiseasesName = dto.v_DiseasesName;
            entity.d_StartDate = dto.d_StartDate;
            entity.v_GroupName = dto.v_GroupName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getantecedentconsolidateforservice2_spResult"/> to an instance of <see cref="getantecedentconsolidateforservice2_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getantecedentconsolidateforservice2_spResult"/> to convert.</param>
        public static getantecedentconsolidateforservice2_spResultDto ToDTO(this getantecedentconsolidateforservice2_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getantecedentconsolidateforservice2_spResultDto();

            dto.v_AntecedentTypeName = entity.v_AntecedentTypeName;
            dto.v_DiseasesId = entity.v_DiseasesId;
            dto.v_CIE10Id = entity.v_CIE10Id;
            dto.v_DiseasesName = entity.v_DiseasesName;
            dto.d_StartDate = entity.d_StartDate;
            dto.v_GroupName = entity.v_GroupName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getantecedentconsolidateforservice2_spResultDto"/> to an instance of <see cref="getantecedentconsolidateforservice2_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getantecedentconsolidateforservice2_spResult> ToEntities(this IEnumerable<getantecedentconsolidateforservice2_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getantecedentconsolidateforservice2_spResult"/> to an instance of <see cref="getantecedentconsolidateforservice2_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getantecedentconsolidateforservice2_spResultDto> ToDTOs(this IEnumerable<getantecedentconsolidateforservice2_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
