//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getanamnesisreport_spResult"/> and <see cref="getanamnesisreport_spResultDto"/>.
    /// </summary>
    public static partial class getanamnesisreport_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getanamnesisreport_spResultDto"/> converted from <see cref="getanamnesisreport_spResult"/>.</param>
        static partial void OnDTO(this getanamnesisreport_spResult entity, getanamnesisreport_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getanamnesisreport_spResult"/> converted from <see cref="getanamnesisreport_spResultDto"/>.</param>
        static partial void OnEntity(this getanamnesisreport_spResultDto dto, getanamnesisreport_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getanamnesisreport_spResultDto"/> to an instance of <see cref="getanamnesisreport_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getanamnesisreport_spResultDto"/> to convert.</param>
        public static getanamnesisreport_spResult ToEntity(this getanamnesisreport_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getanamnesisreport_spResult();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.i_HasSymptomId = dto.i_HasSymptomId;
            entity.v_MainSymptom = dto.v_MainSymptom;
            entity.i_TimeOfDisease = dto.i_TimeOfDisease;
            entity.i_TimeOfDiseaseTypeId = dto.i_TimeOfDiseaseTypeId;
            entity.v_Story = dto.v_Story;
            entity.v_PersonId = dto.v_PersonId;
            entity.i_DreamId = dto.i_DreamId;
            entity.v_Dream = dto.v_Dream;
            entity.i_UrineId = dto.i_UrineId;
            entity.v_Urine = dto.v_Urine;
            entity.i_DepositionId = dto.i_DepositionId;
            entity.v_Deposition = dto.v_Deposition;
            entity.i_AppetiteId = dto.i_AppetiteId;
            entity.v_Appetite = dto.v_Appetite;
            entity.i_ThirstId = dto.i_ThirstId;
            entity.v_Thirst = dto.v_Thirst;
            entity.d_Fur = dto.d_Fur;
            entity.v_CatemenialRegime = dto.v_CatemenialRegime;
            entity.i_MacId = dto.i_MacId;
            entity.v_Mac = dto.v_Mac;
            entity.d_PAP = dto.d_PAP;
            entity.d_Mamografia = dto.d_Mamografia;
            entity.v_CiruGine = dto.v_CiruGine;
            entity.v_Gestapara = dto.v_Gestapara;
            entity.v_Menarquia = dto.v_Menarquia;
            entity.v_Findings = dto.v_Findings;
            entity.FirmaDoctor = dto.FirmaDoctor;
            entity.FirmaMedicoMedicina = dto.FirmaMedicoMedicina;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getanamnesisreport_spResult"/> to an instance of <see cref="getanamnesisreport_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getanamnesisreport_spResult"/> to convert.</param>
        public static getanamnesisreport_spResultDto ToDTO(this getanamnesisreport_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getanamnesisreport_spResultDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.i_HasSymptomId = entity.i_HasSymptomId;
            dto.v_MainSymptom = entity.v_MainSymptom;
            dto.i_TimeOfDisease = entity.i_TimeOfDisease;
            dto.i_TimeOfDiseaseTypeId = entity.i_TimeOfDiseaseTypeId;
            dto.v_Story = entity.v_Story;
            dto.v_PersonId = entity.v_PersonId;
            dto.i_DreamId = entity.i_DreamId;
            dto.v_Dream = entity.v_Dream;
            dto.i_UrineId = entity.i_UrineId;
            dto.v_Urine = entity.v_Urine;
            dto.i_DepositionId = entity.i_DepositionId;
            dto.v_Deposition = entity.v_Deposition;
            dto.i_AppetiteId = entity.i_AppetiteId;
            dto.v_Appetite = entity.v_Appetite;
            dto.i_ThirstId = entity.i_ThirstId;
            dto.v_Thirst = entity.v_Thirst;
            dto.d_Fur = entity.d_Fur;
            dto.v_CatemenialRegime = entity.v_CatemenialRegime;
            dto.i_MacId = entity.i_MacId;
            dto.v_Mac = entity.v_Mac;
            dto.d_PAP = entity.d_PAP;
            dto.d_Mamografia = entity.d_Mamografia;
            dto.v_CiruGine = entity.v_CiruGine;
            dto.v_Gestapara = entity.v_Gestapara;
            dto.v_Menarquia = entity.v_Menarquia;
            dto.v_Findings = entity.v_Findings;
            dto.FirmaDoctor = entity.FirmaDoctor;
            dto.FirmaMedicoMedicina = entity.FirmaMedicoMedicina;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getanamnesisreport_spResultDto"/> to an instance of <see cref="getanamnesisreport_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getanamnesisreport_spResult> ToEntities(this IEnumerable<getanamnesisreport_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getanamnesisreport_spResult"/> to an instance of <see cref="getanamnesisreport_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getanamnesisreport_spResultDto> ToDTOs(this IEnumerable<getanamnesisreport_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
