//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getantecedentconsolidateforservice3_spResult"/> and <see cref="getantecedentconsolidateforservice3_spResultDto"/>.
    /// </summary>
    public static partial class getantecedentconsolidateforservice3_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getantecedentconsolidateforservice3_spResultDto"/> converted from <see cref="getantecedentconsolidateforservice3_spResult"/>.</param>
        static partial void OnDTO(this getantecedentconsolidateforservice3_spResult entity, getantecedentconsolidateforservice3_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getantecedentconsolidateforservice3_spResult"/> converted from <see cref="getantecedentconsolidateforservice3_spResultDto"/>.</param>
        static partial void OnEntity(this getantecedentconsolidateforservice3_spResultDto dto, getantecedentconsolidateforservice3_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getantecedentconsolidateforservice3_spResultDto"/> to an instance of <see cref="getantecedentconsolidateforservice3_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getantecedentconsolidateforservice3_spResultDto"/> to convert.</param>
        public static getantecedentconsolidateforservice3_spResult ToEntity(this getantecedentconsolidateforservice3_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getantecedentconsolidateforservice3_spResult();

            entity.v_AntecedentTypeName = dto.v_AntecedentTypeName;
            entity.i_TypeFamilyId = dto.i_TypeFamilyId;
            entity.v_TypeFamilyName = dto.v_TypeFamilyName;
            entity.v_DiseasesName = dto.v_DiseasesName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getantecedentconsolidateforservice3_spResult"/> to an instance of <see cref="getantecedentconsolidateforservice3_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getantecedentconsolidateforservice3_spResult"/> to convert.</param>
        public static getantecedentconsolidateforservice3_spResultDto ToDTO(this getantecedentconsolidateforservice3_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getantecedentconsolidateforservice3_spResultDto();

            dto.v_AntecedentTypeName = entity.v_AntecedentTypeName;
            dto.i_TypeFamilyId = entity.i_TypeFamilyId;
            dto.v_TypeFamilyName = entity.v_TypeFamilyName;
            dto.v_DiseasesName = entity.v_DiseasesName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getantecedentconsolidateforservice3_spResultDto"/> to an instance of <see cref="getantecedentconsolidateforservice3_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getantecedentconsolidateforservice3_spResult> ToEntities(this IEnumerable<getantecedentconsolidateforservice3_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getantecedentconsolidateforservice3_spResult"/> to an instance of <see cref="getantecedentconsolidateforservice3_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getantecedentconsolidateforservice3_spResultDto> ToDTOs(this IEnumerable<getantecedentconsolidateforservice3_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
