//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getbaucherResult"/> and <see cref="getbaucherResultDto"/>.
    /// </summary>
    public static partial class getbaucherResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getbaucherResultDto"/> converted from <see cref="getbaucherResult"/>.</param>
        static partial void OnDTO(this getbaucherResult entity, getbaucherResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getbaucherResult"/> converted from <see cref="getbaucherResultDto"/>.</param>
        static partial void OnEntity(this getbaucherResultDto dto, getbaucherResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getbaucherResultDto"/> to an instance of <see cref="getbaucherResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getbaucherResultDto"/> to convert.</param>
        public static getbaucherResult ToEntity(this getbaucherResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getbaucherResult();

            entity.v_BaucherName = dto.v_BaucherName;
            entity.b_BaucherContent = dto.b_BaucherContent;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getbaucherResult"/> to an instance of <see cref="getbaucherResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getbaucherResult"/> to convert.</param>
        public static getbaucherResultDto ToDTO(this getbaucherResult entity)
        {
            if (entity == null) return null;

            var dto = new getbaucherResultDto();

            dto.v_BaucherName = entity.v_BaucherName;
            dto.b_BaucherContent = entity.b_BaucherContent;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getbaucherResultDto"/> to an instance of <see cref="getbaucherResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getbaucherResult> ToEntities(this IEnumerable<getbaucherResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getbaucherResult"/> to an instance of <see cref="getbaucherResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getbaucherResultDto> ToDTOs(this IEnumerable<getbaucherResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
