//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getcategoriaexamenfaltanteeso_spResult"/> and <see cref="getcategoriaexamenfaltanteeso_spResultDto"/>.
    /// </summary>
    public static partial class getcategoriaexamenfaltanteeso_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getcategoriaexamenfaltanteeso_spResultDto"/> converted from <see cref="getcategoriaexamenfaltanteeso_spResult"/>.</param>
        static partial void OnDTO(this getcategoriaexamenfaltanteeso_spResult entity, getcategoriaexamenfaltanteeso_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getcategoriaexamenfaltanteeso_spResult"/> converted from <see cref="getcategoriaexamenfaltanteeso_spResultDto"/>.</param>
        static partial void OnEntity(this getcategoriaexamenfaltanteeso_spResultDto dto, getcategoriaexamenfaltanteeso_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getcategoriaexamenfaltanteeso_spResultDto"/> to an instance of <see cref="getcategoriaexamenfaltanteeso_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getcategoriaexamenfaltanteeso_spResultDto"/> to convert.</param>
        public static getcategoriaexamenfaltanteeso_spResult ToEntity(this getcategoriaexamenfaltanteeso_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getcategoriaexamenfaltanteeso_spResult();

            entity.Categorias = dto.Categorias;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getcategoriaexamenfaltanteeso_spResult"/> to an instance of <see cref="getcategoriaexamenfaltanteeso_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getcategoriaexamenfaltanteeso_spResult"/> to convert.</param>
        public static getcategoriaexamenfaltanteeso_spResultDto ToDTO(this getcategoriaexamenfaltanteeso_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getcategoriaexamenfaltanteeso_spResultDto();

            dto.Categorias = entity.Categorias;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getcategoriaexamenfaltanteeso_spResultDto"/> to an instance of <see cref="getcategoriaexamenfaltanteeso_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getcategoriaexamenfaltanteeso_spResult> ToEntities(this IEnumerable<getcategoriaexamenfaltanteeso_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getcategoriaexamenfaltanteeso_spResult"/> to an instance of <see cref="getcategoriaexamenfaltanteeso_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getcategoriaexamenfaltanteeso_spResultDto> ToDTOs(this IEnumerable<getcategoriaexamenfaltanteeso_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
