//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getconcatenateexposiciones_spResult"/> and <see cref="getconcatenateexposiciones_spResultDto"/>.
    /// </summary>
    public static partial class getconcatenateexposiciones_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getconcatenateexposiciones_spResultDto"/> converted from <see cref="getconcatenateexposiciones_spResult"/>.</param>
        static partial void OnDTO(this getconcatenateexposiciones_spResult entity, getconcatenateexposiciones_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getconcatenateexposiciones_spResult"/> converted from <see cref="getconcatenateexposiciones_spResultDto"/>.</param>
        static partial void OnEntity(this getconcatenateexposiciones_spResultDto dto, getconcatenateexposiciones_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getconcatenateexposiciones_spResultDto"/> to an instance of <see cref="getconcatenateexposiciones_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getconcatenateexposiciones_spResultDto"/> to convert.</param>
        public static getconcatenateexposiciones_spResult ToEntity(this getconcatenateexposiciones_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getconcatenateexposiciones_spResult();

            entity.v_Exposicion = dto.v_Exposicion;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getconcatenateexposiciones_spResult"/> to an instance of <see cref="getconcatenateexposiciones_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getconcatenateexposiciones_spResult"/> to convert.</param>
        public static getconcatenateexposiciones_spResultDto ToDTO(this getconcatenateexposiciones_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getconcatenateexposiciones_spResultDto();

            dto.v_Exposicion = entity.v_Exposicion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getconcatenateexposiciones_spResultDto"/> to an instance of <see cref="getconcatenateexposiciones_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getconcatenateexposiciones_spResult> ToEntities(this IEnumerable<getconcatenateexposiciones_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getconcatenateexposiciones_spResult"/> to an instance of <see cref="getconcatenateexposiciones_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getconcatenateexposiciones_spResultDto> ToDTOs(this IEnumerable<getconcatenateexposiciones_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
