//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:14
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getcustionarioaudiometria_spResult"/> and <see cref="getcustionarioaudiometria_spResultDto"/>.
    /// </summary>
    public static partial class getcustionarioaudiometria_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getcustionarioaudiometria_spResultDto"/> converted from <see cref="getcustionarioaudiometria_spResult"/>.</param>
        static partial void OnDTO(this getcustionarioaudiometria_spResult entity, getcustionarioaudiometria_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getcustionarioaudiometria_spResult"/> converted from <see cref="getcustionarioaudiometria_spResultDto"/>.</param>
        static partial void OnEntity(this getcustionarioaudiometria_spResultDto dto, getcustionarioaudiometria_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getcustionarioaudiometria_spResultDto"/> to an instance of <see cref="getcustionarioaudiometria_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getcustionarioaudiometria_spResultDto"/> to convert.</param>
        public static getcustionarioaudiometria_spResult ToEntity(this getcustionarioaudiometria_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getcustionarioaudiometria_spResult();

            entity.NOMBREPACIENTE = dto.NOMBREPACIENTE;
            entity.FechaNacimiento = dto.FechaNacimiento;
            entity.LugarNacimiento = dto.LugarNacimiento;
            entity.EstadoCivil = dto.EstadoCivil;
            entity.GradoInstruccion = dto.GradoInstruccion;
            entity.LugarResidencia = dto.LugarResidencia;
            entity.PuestoTrabajo = dto.PuestoTrabajo;
            entity.TipoESO = dto.TipoESO;
            entity.NombreEmpresa = dto.NombreEmpresa;
            entity.ActividadEmpresa = dto.ActividadEmpresa;
            entity.FechaEvaluacion = dto.FechaEvaluacion;
            entity.IdServicio = dto.IdServicio;
            entity.AreaTrabajo = dto.AreaTrabajo;
            entity.FIRMAMEDICO = dto.FIRMAMEDICO;
            entity.DNI = dto.DNI;
            entity.GENERO = dto.GENERO;
            entity.FIRMAPACIENTE = dto.FIRMAPACIENTE;
            entity.HuellaPACIENTE = dto.HuellaPACIENTE;
            entity.LOGOCLIENTE = dto.LOGOCLIENTE;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getcustionarioaudiometria_spResult"/> to an instance of <see cref="getcustionarioaudiometria_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getcustionarioaudiometria_spResult"/> to convert.</param>
        public static getcustionarioaudiometria_spResultDto ToDTO(this getcustionarioaudiometria_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getcustionarioaudiometria_spResultDto();

            dto.NOMBREPACIENTE = entity.NOMBREPACIENTE;
            dto.FechaNacimiento = entity.FechaNacimiento;
            dto.LugarNacimiento = entity.LugarNacimiento;
            dto.EstadoCivil = entity.EstadoCivil;
            dto.GradoInstruccion = entity.GradoInstruccion;
            dto.LugarResidencia = entity.LugarResidencia;
            dto.PuestoTrabajo = entity.PuestoTrabajo;
            dto.TipoESO = entity.TipoESO;
            dto.NombreEmpresa = entity.NombreEmpresa;
            dto.ActividadEmpresa = entity.ActividadEmpresa;
            dto.FechaEvaluacion = entity.FechaEvaluacion;
            dto.IdServicio = entity.IdServicio;
            dto.AreaTrabajo = entity.AreaTrabajo;
            dto.FIRMAMEDICO = entity.FIRMAMEDICO;
            dto.DNI = entity.DNI;
            dto.GENERO = entity.GENERO;
            dto.FIRMAPACIENTE = entity.FIRMAPACIENTE;
            dto.HuellaPACIENTE = entity.HuellaPACIENTE;
            dto.LOGOCLIENTE = entity.LOGOCLIENTE;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getcustionarioaudiometria_spResultDto"/> to an instance of <see cref="getcustionarioaudiometria_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getcustionarioaudiometria_spResult> ToEntities(this IEnumerable<getcustionarioaudiometria_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getcustionarioaudiometria_spResult"/> to an instance of <see cref="getcustionarioaudiometria_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getcustionarioaudiometria_spResultDto> ToDTOs(this IEnumerable<getcustionarioaudiometria_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
