//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getdevolveraptitud_spResult"/> and <see cref="getdevolveraptitud_spResultDto"/>.
    /// </summary>
    public static partial class getdevolveraptitud_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getdevolveraptitud_spResultDto"/> converted from <see cref="getdevolveraptitud_spResult"/>.</param>
        static partial void OnDTO(this getdevolveraptitud_spResult entity, getdevolveraptitud_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getdevolveraptitud_spResult"/> converted from <see cref="getdevolveraptitud_spResultDto"/>.</param>
        static partial void OnEntity(this getdevolveraptitud_spResultDto dto, getdevolveraptitud_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getdevolveraptitud_spResultDto"/> to an instance of <see cref="getdevolveraptitud_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getdevolveraptitud_spResultDto"/> to convert.</param>
        public static getdevolveraptitud_spResult ToEntity(this getdevolveraptitud_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getdevolveraptitud_spResult();

            entity.Aptitud = dto.Aptitud;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getdevolveraptitud_spResult"/> to an instance of <see cref="getdevolveraptitud_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getdevolveraptitud_spResult"/> to convert.</param>
        public static getdevolveraptitud_spResultDto ToDTO(this getdevolveraptitud_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getdevolveraptitud_spResultDto();

            dto.Aptitud = entity.Aptitud;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getdevolveraptitud_spResultDto"/> to an instance of <see cref="getdevolveraptitud_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getdevolveraptitud_spResult> ToEntities(this IEnumerable<getdevolveraptitud_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getdevolveraptitud_spResult"/> to an instance of <see cref="getdevolveraptitud_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getdevolveraptitud_spResultDto> ToDTOs(this IEnumerable<getdevolveraptitud_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
