//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getdevolverdatosusuariofirma_spResult"/> and <see cref="getdevolverdatosusuariofirma_spResultDto"/>.
    /// </summary>
    public static partial class getdevolverdatosusuariofirma_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getdevolverdatosusuariofirma_spResultDto"/> converted from <see cref="getdevolverdatosusuariofirma_spResult"/>.</param>
        static partial void OnDTO(this getdevolverdatosusuariofirma_spResult entity, getdevolverdatosusuariofirma_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getdevolverdatosusuariofirma_spResult"/> converted from <see cref="getdevolverdatosusuariofirma_spResultDto"/>.</param>
        static partial void OnEntity(this getdevolverdatosusuariofirma_spResultDto dto, getdevolverdatosusuariofirma_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getdevolverdatosusuariofirma_spResultDto"/> to an instance of <see cref="getdevolverdatosusuariofirma_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getdevolverdatosusuariofirma_spResultDto"/> to convert.</param>
        public static getdevolverdatosusuariofirma_spResult ToEntity(this getdevolverdatosusuariofirma_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getdevolverdatosusuariofirma_spResult();

            entity.Firma = dto.Firma;
            entity.Nombre = dto.Nombre;
            entity.CMP = dto.CMP;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getdevolverdatosusuariofirma_spResult"/> to an instance of <see cref="getdevolverdatosusuariofirma_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getdevolverdatosusuariofirma_spResult"/> to convert.</param>
        public static getdevolverdatosusuariofirma_spResultDto ToDTO(this getdevolverdatosusuariofirma_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getdevolverdatosusuariofirma_spResultDto();

            dto.Firma = entity.Firma;
            dto.Nombre = entity.Nombre;
            dto.CMP = entity.CMP;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getdevolverdatosusuariofirma_spResultDto"/> to an instance of <see cref="getdevolverdatosusuariofirma_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getdevolverdatosusuariofirma_spResult> ToEntities(this IEnumerable<getdevolverdatosusuariofirma_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getdevolverdatosusuariofirma_spResult"/> to an instance of <see cref="getdevolverdatosusuariofirma_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getdevolverdatosusuariofirma_spResultDto> ToDTOs(this IEnumerable<getdevolverdatosusuariofirma_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
