//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getdiseasespagedandfiltered_spResult"/> and <see cref="getdiseasespagedandfiltered_spResultDto"/>.
    /// </summary>
    public static partial class getdiseasespagedandfiltered_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getdiseasespagedandfiltered_spResultDto"/> converted from <see cref="getdiseasespagedandfiltered_spResult"/>.</param>
        static partial void OnDTO(this getdiseasespagedandfiltered_spResult entity, getdiseasespagedandfiltered_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getdiseasespagedandfiltered_spResult"/> converted from <see cref="getdiseasespagedandfiltered_spResultDto"/>.</param>
        static partial void OnEntity(this getdiseasespagedandfiltered_spResultDto dto, getdiseasespagedandfiltered_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getdiseasespagedandfiltered_spResultDto"/> to an instance of <see cref="getdiseasespagedandfiltered_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getdiseasespagedandfiltered_spResultDto"/> to convert.</param>
        public static getdiseasespagedandfiltered_spResult ToEntity(this getdiseasespagedandfiltered_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getdiseasespagedandfiltered_spResult();

            entity.v_DiseasesId = dto.v_DiseasesId;
            entity.v_CIE10Id = dto.v_CIE10Id;
            entity.v_Name = dto.v_Name;
            entity.v_CIE10Description1 = dto.v_CIE10Description1;
            entity.v_CreationUser = dto.v_CreationUser;
            entity.v_UpdateUser = dto.v_UpdateUser;
            entity.d_CreationDate = dto.d_CreationDate;
            entity.d_UpdateDate = dto.d_UpdateDate;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getdiseasespagedandfiltered_spResult"/> to an instance of <see cref="getdiseasespagedandfiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getdiseasespagedandfiltered_spResult"/> to convert.</param>
        public static getdiseasespagedandfiltered_spResultDto ToDTO(this getdiseasespagedandfiltered_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getdiseasespagedandfiltered_spResultDto();

            dto.v_DiseasesId = entity.v_DiseasesId;
            dto.v_CIE10Id = entity.v_CIE10Id;
            dto.v_Name = entity.v_Name;
            dto.v_CIE10Description1 = entity.v_CIE10Description1;
            dto.v_CreationUser = entity.v_CreationUser;
            dto.v_UpdateUser = entity.v_UpdateUser;
            dto.d_CreationDate = entity.d_CreationDate;
            dto.d_UpdateDate = entity.d_UpdateDate;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getdiseasespagedandfiltered_spResultDto"/> to an instance of <see cref="getdiseasespagedandfiltered_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getdiseasespagedandfiltered_spResult> ToEntities(this IEnumerable<getdiseasespagedandfiltered_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getdiseasespagedandfiltered_spResult"/> to an instance of <see cref="getdiseasespagedandfiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getdiseasespagedandfiltered_spResultDto> ToDTOs(this IEnumerable<getdiseasespagedandfiltered_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
