//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getembarazofiltered_spResult"/> and <see cref="getembarazofiltered_spResultDto"/>.
    /// </summary>
    public static partial class getembarazofiltered_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getembarazofiltered_spResultDto"/> converted from <see cref="getembarazofiltered_spResult"/>.</param>
        static partial void OnDTO(this getembarazofiltered_spResult entity, getembarazofiltered_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getembarazofiltered_spResult"/> converted from <see cref="getembarazofiltered_spResultDto"/>.</param>
        static partial void OnEntity(this getembarazofiltered_spResultDto dto, getembarazofiltered_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getembarazofiltered_spResultDto"/> to an instance of <see cref="getembarazofiltered_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getembarazofiltered_spResultDto"/> to convert.</param>
        public static getembarazofiltered_spResult ToEntity(this getembarazofiltered_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getembarazofiltered_spResult();

            entity.v_EmbarazoId = dto.v_EmbarazoId;
            entity.v_PersonId = dto.v_PersonId;
            entity.v_Anio = dto.v_Anio;
            entity.v_Cpn = dto.v_Cpn;
            entity.v_Complicacion = dto.v_Complicacion;
            entity.v_Parto = dto.v_Parto;
            entity.v_PesoRn = dto.v_PesoRn;
            entity.v_Puerpio = dto.v_Puerpio;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getembarazofiltered_spResult"/> to an instance of <see cref="getembarazofiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getembarazofiltered_spResult"/> to convert.</param>
        public static getembarazofiltered_spResultDto ToDTO(this getembarazofiltered_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getembarazofiltered_spResultDto();

            dto.v_EmbarazoId = entity.v_EmbarazoId;
            dto.v_PersonId = entity.v_PersonId;
            dto.v_Anio = entity.v_Anio;
            dto.v_Cpn = entity.v_Cpn;
            dto.v_Complicacion = entity.v_Complicacion;
            dto.v_Parto = entity.v_Parto;
            dto.v_PesoRn = entity.v_PesoRn;
            dto.v_Puerpio = entity.v_Puerpio;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getembarazofiltered_spResultDto"/> to an instance of <see cref="getembarazofiltered_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getembarazofiltered_spResult> ToEntities(this IEnumerable<getembarazofiltered_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getembarazofiltered_spResult"/> to an instance of <see cref="getembarazofiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getembarazofiltered_spResultDto> ToDTOs(this IEnumerable<getembarazofiltered_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
