//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getformaction_spResult"/> and <see cref="getformaction_spResultDto"/>.
    /// </summary>
    public static partial class getformaction_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getformaction_spResultDto"/> converted from <see cref="getformaction_spResult"/>.</param>
        static partial void OnDTO(this getformaction_spResult entity, getformaction_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getformaction_spResult"/> converted from <see cref="getformaction_spResultDto"/>.</param>
        static partial void OnEntity(this getformaction_spResultDto dto, getformaction_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getformaction_spResultDto"/> to an instance of <see cref="getformaction_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getformaction_spResultDto"/> to convert.</param>
        public static getformaction_spResult ToEntity(this getformaction_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getformaction_spResult();

            entity.Value1 = dto.Value1;
            entity.Value2 = dto.Value2;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getformaction_spResult"/> to an instance of <see cref="getformaction_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getformaction_spResult"/> to convert.</param>
        public static getformaction_spResultDto ToDTO(this getformaction_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getformaction_spResultDto();

            dto.Value1 = entity.Value1;
            dto.Value2 = entity.Value2;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getformaction_spResultDto"/> to an instance of <see cref="getformaction_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getformaction_spResult> ToEntities(this IEnumerable<getformaction_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getformaction_spResult"/> to an instance of <see cref="getformaction_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getformaction_spResultDto> ToDTOs(this IEnumerable<getformaction_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
