//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="gethospitalizacionpagedandfiltered_1Result"/> and <see cref="gethospitalizacionpagedandfiltered_1ResultDto"/>.
    /// </summary>
    public static partial class gethospitalizacionpagedandfiltered_1ResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="gethospitalizacionpagedandfiltered_1ResultDto"/> converted from <see cref="gethospitalizacionpagedandfiltered_1Result"/>.</param>
        static partial void OnDTO(this gethospitalizacionpagedandfiltered_1Result entity, gethospitalizacionpagedandfiltered_1ResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="gethospitalizacionpagedandfiltered_1Result"/> converted from <see cref="gethospitalizacionpagedandfiltered_1ResultDto"/>.</param>
        static partial void OnEntity(this gethospitalizacionpagedandfiltered_1ResultDto dto, gethospitalizacionpagedandfiltered_1Result entity);

        /// <summary>
        /// Converts this instance of <see cref="gethospitalizacionpagedandfiltered_1ResultDto"/> to an instance of <see cref="gethospitalizacionpagedandfiltered_1Result"/>.
        /// </summary>
        /// <param name="dto"><see cref="gethospitalizacionpagedandfiltered_1ResultDto"/> to convert.</param>
        public static gethospitalizacionpagedandfiltered_1Result ToEntity(this gethospitalizacionpagedandfiltered_1ResultDto dto)
        {
            if (dto == null) return null;

            var entity = new gethospitalizacionpagedandfiltered_1Result();

            entity.d_FechaIngreso = dto.d_FechaIngreso;
            entity.d_FechaAlta = dto.d_FechaAlta;
            entity.v_Paciente = dto.v_Paciente;
            entity.v_HopitalizacionId = dto.v_HopitalizacionId;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.v_PersonId = dto.v_PersonId;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.d_Birthdate = dto.d_Birthdate;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.v_Comentario = dto.v_Comentario;
            entity.v_NroLiquidacion = dto.v_NroLiquidacion;
            entity.d_PagoMedico = dto.d_PagoMedico;
            entity.i_MedicoPago = dto.i_MedicoPago;
            entity.d_PagoPaciente = dto.d_PagoPaciente;
            entity.i_PacientePago = dto.i_PacientePago;
            entity.v_MedicoTratante = dto.v_MedicoTratante;
            entity.v_MedicoTratante1 = dto.v_MedicoTratante1;
            entity.v_Servicio = dto.v_Servicio;
            entity.v_Cie10 = dto.v_Cie10;
            entity.v_Diagnostico = dto.v_Diagnostico;
            entity.i_Years = dto.i_Years;
            entity.v_ProcedenciaPac = dto.v_ProcedenciaPac;
            entity.v_Comprobantes = dto.v_Comprobantes;
            entity.d_MontoPagado = dto.d_MontoPagado;
            entity.Sop = dto.Sop;
            entity.Hosp = dto.Hosp;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="gethospitalizacionpagedandfiltered_1Result"/> to an instance of <see cref="gethospitalizacionpagedandfiltered_1ResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="gethospitalizacionpagedandfiltered_1Result"/> to convert.</param>
        public static gethospitalizacionpagedandfiltered_1ResultDto ToDTO(this gethospitalizacionpagedandfiltered_1Result entity)
        {
            if (entity == null) return null;

            var dto = new gethospitalizacionpagedandfiltered_1ResultDto();

            dto.d_FechaIngreso = entity.d_FechaIngreso;
            dto.d_FechaAlta = entity.d_FechaAlta;
            dto.v_Paciente = entity.v_Paciente;
            dto.v_HopitalizacionId = entity.v_HopitalizacionId;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.v_PersonId = entity.v_PersonId;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.d_Birthdate = entity.d_Birthdate;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.v_Comentario = entity.v_Comentario;
            dto.v_NroLiquidacion = entity.v_NroLiquidacion;
            dto.d_PagoMedico = entity.d_PagoMedico;
            dto.i_MedicoPago = entity.i_MedicoPago;
            dto.d_PagoPaciente = entity.d_PagoPaciente;
            dto.i_PacientePago = entity.i_PacientePago;
            dto.v_MedicoTratante = entity.v_MedicoTratante;
            dto.v_MedicoTratante1 = entity.v_MedicoTratante1;
            dto.v_Servicio = entity.v_Servicio;
            dto.v_Cie10 = entity.v_Cie10;
            dto.v_Diagnostico = entity.v_Diagnostico;
            dto.i_Years = entity.i_Years;
            dto.v_ProcedenciaPac = entity.v_ProcedenciaPac;
            dto.v_Comprobantes = entity.v_Comprobantes;
            dto.d_MontoPagado = entity.d_MontoPagado;
            dto.Sop = entity.Sop;
            dto.Hosp = entity.Hosp;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="gethospitalizacionpagedandfiltered_1ResultDto"/> to an instance of <see cref="gethospitalizacionpagedandfiltered_1Result"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<gethospitalizacionpagedandfiltered_1Result> ToEntities(this IEnumerable<gethospitalizacionpagedandfiltered_1ResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="gethospitalizacionpagedandfiltered_1Result"/> to an instance of <see cref="gethospitalizacionpagedandfiltered_1ResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<gethospitalizacionpagedandfiltered_1ResultDto> ToDTOs(this IEnumerable<gethospitalizacionpagedandfiltered_1Result> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
