//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="gethistorypagedandfiltered_spResult"/> and <see cref="gethistorypagedandfiltered_spResultDto"/>.
    /// </summary>
    public static partial class gethistorypagedandfiltered_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="gethistorypagedandfiltered_spResultDto"/> converted from <see cref="gethistorypagedandfiltered_spResult"/>.</param>
        static partial void OnDTO(this gethistorypagedandfiltered_spResult entity, gethistorypagedandfiltered_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="gethistorypagedandfiltered_spResult"/> converted from <see cref="gethistorypagedandfiltered_spResultDto"/>.</param>
        static partial void OnEntity(this gethistorypagedandfiltered_spResultDto dto, gethistorypagedandfiltered_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="gethistorypagedandfiltered_spResultDto"/> to an instance of <see cref="gethistorypagedandfiltered_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="gethistorypagedandfiltered_spResultDto"/> to convert.</param>
        public static gethistorypagedandfiltered_spResult ToEntity(this gethistorypagedandfiltered_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new gethistorypagedandfiltered_spResult();

            entity.v_HistoryId = dto.v_HistoryId;
            entity.d_StartDate = dto.d_StartDate;
            entity.d_EndDate = dto.d_EndDate;
            entity.v_Organization = dto.v_Organization;
            entity.v_TypeActivity = dto.v_TypeActivity;
            entity.i_GeografixcaHeight = dto.i_GeografixcaHeight;
            entity.v_workstation = dto.v_workstation;
            entity.v_CreationUser = dto.v_CreationUser;
            entity.v_UpdateUser = dto.v_UpdateUser;
            entity.d_CreationDate = dto.d_CreationDate;
            entity.d_UpdateDate = dto.d_UpdateDate;
            entity.b_FingerPrintImage = dto.b_FingerPrintImage;
            entity.b_RubricImage = dto.b_RubricImage;
            entity.t_RubricImageText = dto.t_RubricImageText;
            entity.i_Trabajo_Actual = dto.i_Trabajo_Actual;
            entity.v_TypeOperationName = dto.v_TypeOperationName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="gethistorypagedandfiltered_spResult"/> to an instance of <see cref="gethistorypagedandfiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="gethistorypagedandfiltered_spResult"/> to convert.</param>
        public static gethistorypagedandfiltered_spResultDto ToDTO(this gethistorypagedandfiltered_spResult entity)
        {
            if (entity == null) return null;

            var dto = new gethistorypagedandfiltered_spResultDto();

            dto.v_HistoryId = entity.v_HistoryId;
            dto.d_StartDate = entity.d_StartDate;
            dto.d_EndDate = entity.d_EndDate;
            dto.v_Organization = entity.v_Organization;
            dto.v_TypeActivity = entity.v_TypeActivity;
            dto.i_GeografixcaHeight = entity.i_GeografixcaHeight;
            dto.v_workstation = entity.v_workstation;
            dto.v_CreationUser = entity.v_CreationUser;
            dto.v_UpdateUser = entity.v_UpdateUser;
            dto.d_CreationDate = entity.d_CreationDate;
            dto.d_UpdateDate = entity.d_UpdateDate;
            dto.b_FingerPrintImage = entity.b_FingerPrintImage;
            dto.b_RubricImage = entity.b_RubricImage;
            dto.t_RubricImageText = entity.t_RubricImageText;
            dto.i_Trabajo_Actual = entity.i_Trabajo_Actual;
            dto.v_TypeOperationName = entity.v_TypeOperationName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="gethistorypagedandfiltered_spResultDto"/> to an instance of <see cref="gethistorypagedandfiltered_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<gethistorypagedandfiltered_spResult> ToEntities(this IEnumerable<gethistorypagedandfiltered_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="gethistorypagedandfiltered_spResult"/> to an instance of <see cref="gethistorypagedandfiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<gethistorypagedandfiltered_spResultDto> ToDTOs(this IEnumerable<gethistorypagedandfiltered_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
