//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getinfouserclientResult"/> and <see cref="getinfouserclientResultDto"/>.
    /// </summary>
    public static partial class getinfouserclientResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getinfouserclientResultDto"/> converted from <see cref="getinfouserclientResult"/>.</param>
        static partial void OnDTO(this getinfouserclientResult entity, getinfouserclientResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getinfouserclientResult"/> converted from <see cref="getinfouserclientResultDto"/>.</param>
        static partial void OnEntity(this getinfouserclientResultDto dto, getinfouserclientResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getinfouserclientResultDto"/> to an instance of <see cref="getinfouserclientResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getinfouserclientResultDto"/> to convert.</param>
        public static getinfouserclientResult ToEntity(this getinfouserclientResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getinfouserclientResult();

            entity.v_Mail = dto.v_Mail;
            entity.v_TelephoneNumber = dto.v_TelephoneNumber;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.v_Name = dto.v_Name;
            entity.i_MasterServiceTypeId = dto.i_MasterServiceTypeId;
            entity.name = dto.name;
            entity.v_PersonId = dto.v_PersonId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getinfouserclientResult"/> to an instance of <see cref="getinfouserclientResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getinfouserclientResult"/> to convert.</param>
        public static getinfouserclientResultDto ToDTO(this getinfouserclientResult entity)
        {
            if (entity == null) return null;

            var dto = new getinfouserclientResultDto();

            dto.v_Mail = entity.v_Mail;
            dto.v_TelephoneNumber = entity.v_TelephoneNumber;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.v_Name = entity.v_Name;
            dto.i_MasterServiceTypeId = entity.i_MasterServiceTypeId;
            dto.name = entity.name;
            dto.v_PersonId = entity.v_PersonId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getinfouserclientResultDto"/> to an instance of <see cref="getinfouserclientResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getinfouserclientResult> ToEntities(this IEnumerable<getinfouserclientResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getinfouserclientResult"/> to an instance of <see cref="getinfouserclientResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getinfouserclientResultDto> ToDTOs(this IEnumerable<getinfouserclientResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
