//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getinfopaymentResult"/> and <see cref="getinfopaymentResultDto"/>.
    /// </summary>
    public static partial class getinfopaymentResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getinfopaymentResultDto"/> converted from <see cref="getinfopaymentResult"/>.</param>
        static partial void OnDTO(this getinfopaymentResult entity, getinfopaymentResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getinfopaymentResult"/> converted from <see cref="getinfopaymentResultDto"/>.</param>
        static partial void OnEntity(this getinfopaymentResultDto dto, getinfopaymentResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getinfopaymentResultDto"/> to an instance of <see cref="getinfopaymentResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getinfopaymentResultDto"/> to convert.</param>
        public static getinfopaymentResult ToEntity(this getinfopaymentResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getinfopaymentResult();

            entity.v_NroDoc = dto.v_NroDoc;
            entity.v_paymentType = dto.v_paymentType;
            entity.v_TypeDoc = dto.v_TypeDoc;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getinfopaymentResult"/> to an instance of <see cref="getinfopaymentResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getinfopaymentResult"/> to convert.</param>
        public static getinfopaymentResultDto ToDTO(this getinfopaymentResult entity)
        {
            if (entity == null) return null;

            var dto = new getinfopaymentResultDto();

            dto.v_NroDoc = entity.v_NroDoc;
            dto.v_paymentType = entity.v_paymentType;
            dto.v_TypeDoc = entity.v_TypeDoc;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getinfopaymentResultDto"/> to an instance of <see cref="getinfopaymentResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getinfopaymentResult> ToEntities(this IEnumerable<getinfopaymentResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getinfopaymentResult"/> to an instance of <see cref="getinfopaymentResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getinfopaymentResultDto> ToDTOs(this IEnumerable<getinfopaymentResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
