//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getlistvaluecomponent_spResult"/> and <see cref="getlistvaluecomponent_spResultDto"/>.
    /// </summary>
    public static partial class getlistvaluecomponent_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getlistvaluecomponent_spResultDto"/> converted from <see cref="getlistvaluecomponent_spResult"/>.</param>
        static partial void OnDTO(this getlistvaluecomponent_spResult entity, getlistvaluecomponent_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getlistvaluecomponent_spResult"/> converted from <see cref="getlistvaluecomponent_spResultDto"/>.</param>
        static partial void OnEntity(this getlistvaluecomponent_spResultDto dto, getlistvaluecomponent_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getlistvaluecomponent_spResultDto"/> to an instance of <see cref="getlistvaluecomponent_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getlistvaluecomponent_spResultDto"/> to convert.</param>
        public static getlistvaluecomponent_spResult ToEntity(this getlistvaluecomponent_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getlistvaluecomponent_spResult();

            entity.ServicioId = dto.ServicioId;
            entity.Valor = dto.Valor;
            entity.NombreComponente = dto.NombreComponente;
            entity.IdComponente = dto.IdComponente;
            entity.NombreCampo = dto.NombreCampo;
            entity.IdCampo = dto.IdCampo;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getlistvaluecomponent_spResult"/> to an instance of <see cref="getlistvaluecomponent_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getlistvaluecomponent_spResult"/> to convert.</param>
        public static getlistvaluecomponent_spResultDto ToDTO(this getlistvaluecomponent_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getlistvaluecomponent_spResultDto();

            dto.ServicioId = entity.ServicioId;
            dto.Valor = entity.Valor;
            dto.NombreComponente = entity.NombreComponente;
            dto.IdComponente = entity.IdComponente;
            dto.NombreCampo = entity.NombreCampo;
            dto.IdCampo = entity.IdCampo;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getlistvaluecomponent_spResultDto"/> to an instance of <see cref="getlistvaluecomponent_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getlistvaluecomponent_spResult> ToEntities(this IEnumerable<getlistvaluecomponent_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getlistvaluecomponent_spResult"/> to an instance of <see cref="getlistvaluecomponent_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getlistvaluecomponent_spResultDto> ToDTOs(this IEnumerable<getlistvaluecomponent_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
