//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getlistaatencionesparahistoria_spResult"/> and <see cref="getlistaatencionesparahistoria_spResultDto"/>.
    /// </summary>
    public static partial class getlistaatencionesparahistoria_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getlistaatencionesparahistoria_spResultDto"/> converted from <see cref="getlistaatencionesparahistoria_spResult"/>.</param>
        static partial void OnDTO(this getlistaatencionesparahistoria_spResult entity, getlistaatencionesparahistoria_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getlistaatencionesparahistoria_spResult"/> converted from <see cref="getlistaatencionesparahistoria_spResultDto"/>.</param>
        static partial void OnEntity(this getlistaatencionesparahistoria_spResultDto dto, getlistaatencionesparahistoria_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getlistaatencionesparahistoria_spResultDto"/> to an instance of <see cref="getlistaatencionesparahistoria_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getlistaatencionesparahistoria_spResultDto"/> to convert.</param>
        public static getlistaatencionesparahistoria_spResult ToEntity(this getlistaatencionesparahistoria_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getlistaatencionesparahistoria_spResult();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.Medico = dto.Medico;
            entity.v_Name = dto.v_Name;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.Historia = dto.Historia;
            entity.Interconsultas = dto.Interconsultas;
            entity.Recetas = dto.Recetas;
            entity.Ordenes = dto.Ordenes;
            entity.Anexos = dto.Anexos;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getlistaatencionesparahistoria_spResult"/> to an instance of <see cref="getlistaatencionesparahistoria_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getlistaatencionesparahistoria_spResult"/> to convert.</param>
        public static getlistaatencionesparahistoria_spResultDto ToDTO(this getlistaatencionesparahistoria_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getlistaatencionesparahistoria_spResultDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.Medico = entity.Medico;
            dto.v_Name = entity.v_Name;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.Historia = entity.Historia;
            dto.Interconsultas = entity.Interconsultas;
            dto.Recetas = entity.Recetas;
            dto.Ordenes = entity.Ordenes;
            dto.Anexos = entity.Anexos;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getlistaatencionesparahistoria_spResultDto"/> to an instance of <see cref="getlistaatencionesparahistoria_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getlistaatencionesparahistoria_spResult> ToEntities(this IEnumerable<getlistaatencionesparahistoria_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getlistaatencionesparahistoria_spResult"/> to an instance of <see cref="getlistaatencionesparahistoria_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getlistaatencionesparahistoria_spResultDto> ToDTOs(this IEnumerable<getlistaatencionesparahistoria_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
