//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:32:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getnombremedicolab_spResult"/> and <see cref="getnombremedicolab_spResultDto"/>.
    /// </summary>
    public static partial class getnombremedicolab_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getnombremedicolab_spResultDto"/> converted from <see cref="getnombremedicolab_spResult"/>.</param>
        static partial void OnDTO(this getnombremedicolab_spResult entity, getnombremedicolab_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getnombremedicolab_spResult"/> converted from <see cref="getnombremedicolab_spResultDto"/>.</param>
        static partial void OnEntity(this getnombremedicolab_spResultDto dto, getnombremedicolab_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getnombremedicolab_spResultDto"/> to an instance of <see cref="getnombremedicolab_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getnombremedicolab_spResultDto"/> to convert.</param>
        public static getnombremedicolab_spResult ToEntity(this getnombremedicolab_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getnombremedicolab_spResult();

            entity.Medico = dto.Medico;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getnombremedicolab_spResult"/> to an instance of <see cref="getnombremedicolab_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getnombremedicolab_spResult"/> to convert.</param>
        public static getnombremedicolab_spResultDto ToDTO(this getnombremedicolab_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getnombremedicolab_spResultDto();

            dto.Medico = entity.Medico;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getnombremedicolab_spResultDto"/> to an instance of <see cref="getnombremedicolab_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getnombremedicolab_spResult> ToEntities(this IEnumerable<getnombremedicolab_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getnombremedicolab_spResult"/> to an instance of <see cref="getnombremedicolab_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getnombremedicolab_spResultDto> ToDTOs(this IEnumerable<getnombremedicolab_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
