//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getobtenerfirmamedico_2_spResult"/> and <see cref="getobtenerfirmamedico_2_spResultDto"/>.
    /// </summary>
    public static partial class getobtenerfirmamedico_2_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getobtenerfirmamedico_2_spResultDto"/> converted from <see cref="getobtenerfirmamedico_2_spResult"/>.</param>
        static partial void OnDTO(this getobtenerfirmamedico_2_spResult entity, getobtenerfirmamedico_2_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getobtenerfirmamedico_2_spResult"/> converted from <see cref="getobtenerfirmamedico_2_spResultDto"/>.</param>
        static partial void OnEntity(this getobtenerfirmamedico_2_spResultDto dto, getobtenerfirmamedico_2_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getobtenerfirmamedico_2_spResultDto"/> to an instance of <see cref="getobtenerfirmamedico_2_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getobtenerfirmamedico_2_spResultDto"/> to convert.</param>
        public static getobtenerfirmamedico_2_spResult ToEntity(this getobtenerfirmamedico_2_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getobtenerfirmamedico_2_spResult();

            entity.Value5 = dto.Value5;
            entity.Value2 = dto.Value2;
            entity.Value3 = dto.Value3;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getobtenerfirmamedico_2_spResult"/> to an instance of <see cref="getobtenerfirmamedico_2_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getobtenerfirmamedico_2_spResult"/> to convert.</param>
        public static getobtenerfirmamedico_2_spResultDto ToDTO(this getobtenerfirmamedico_2_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getobtenerfirmamedico_2_spResultDto();

            dto.Value5 = entity.Value5;
            dto.Value2 = entity.Value2;
            dto.Value3 = entity.Value3;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getobtenerfirmamedico_2_spResultDto"/> to an instance of <see cref="getobtenerfirmamedico_2_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getobtenerfirmamedico_2_spResult> ToEntities(this IEnumerable<getobtenerfirmamedico_2_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getobtenerfirmamedico_2_spResult"/> to an instance of <see cref="getobtenerfirmamedico_2_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getobtenerfirmamedico_2_spResultDto> ToDTOs(this IEnumerable<getobtenerfirmamedico_2_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
