//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getobtenerfechascuidadospreventivos__spResult"/> and <see cref="getobtenerfechascuidadospreventivos__spResultDto"/>.
    /// </summary>
    public static partial class getobtenerfechascuidadospreventivos__spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getobtenerfechascuidadospreventivos__spResultDto"/> converted from <see cref="getobtenerfechascuidadospreventivos__spResult"/>.</param>
        static partial void OnDTO(this getobtenerfechascuidadospreventivos__spResult entity, getobtenerfechascuidadospreventivos__spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getobtenerfechascuidadospreventivos__spResult"/> converted from <see cref="getobtenerfechascuidadospreventivos__spResultDto"/>.</param>
        static partial void OnEntity(this getobtenerfechascuidadospreventivos__spResultDto dto, getobtenerfechascuidadospreventivos__spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getobtenerfechascuidadospreventivos__spResultDto"/> to an instance of <see cref="getobtenerfechascuidadospreventivos__spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getobtenerfechascuidadospreventivos__spResultDto"/> to convert.</param>
        public static getobtenerfechascuidadospreventivos__spResult ToEntity(this getobtenerfechascuidadospreventivos__spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getobtenerfechascuidadospreventivos__spResult();

            entity.FechaServicio = dto.FechaServicio;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getobtenerfechascuidadospreventivos__spResult"/> to an instance of <see cref="getobtenerfechascuidadospreventivos__spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getobtenerfechascuidadospreventivos__spResult"/> to convert.</param>
        public static getobtenerfechascuidadospreventivos__spResultDto ToDTO(this getobtenerfechascuidadospreventivos__spResult entity)
        {
            if (entity == null) return null;

            var dto = new getobtenerfechascuidadospreventivos__spResultDto();

            dto.FechaServicio = entity.FechaServicio;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getobtenerfechascuidadospreventivos__spResultDto"/> to an instance of <see cref="getobtenerfechascuidadospreventivos__spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getobtenerfechascuidadospreventivos__spResult> ToEntities(this IEnumerable<getobtenerfechascuidadospreventivos__spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getobtenerfechascuidadospreventivos__spResult"/> to an instance of <see cref="getobtenerfechascuidadospreventivos__spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getobtenerfechascuidadospreventivos__spResultDto> ToDTOs(this IEnumerable<getobtenerfechascuidadospreventivos__spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
