//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getobtenerusuarioanterior_spResult"/> and <see cref="getobtenerusuarioanterior_spResultDto"/>.
    /// </summary>
    public static partial class getobtenerusuarioanterior_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getobtenerusuarioanterior_spResultDto"/> converted from <see cref="getobtenerusuarioanterior_spResult"/>.</param>
        static partial void OnDTO(this getobtenerusuarioanterior_spResult entity, getobtenerusuarioanterior_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getobtenerusuarioanterior_spResult"/> converted from <see cref="getobtenerusuarioanterior_spResultDto"/>.</param>
        static partial void OnEntity(this getobtenerusuarioanterior_spResultDto dto, getobtenerusuarioanterior_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getobtenerusuarioanterior_spResultDto"/> to an instance of <see cref="getobtenerusuarioanterior_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getobtenerusuarioanterior_spResultDto"/> to convert.</param>
        public static getobtenerusuarioanterior_spResult ToEntity(this getobtenerusuarioanterior_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getobtenerusuarioanterior_spResult();

            entity.i_ApprovedUpdateUserId = dto.i_ApprovedUpdateUserId;
            entity.i_ProfessionId = dto.i_ProfessionId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getobtenerusuarioanterior_spResult"/> to an instance of <see cref="getobtenerusuarioanterior_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getobtenerusuarioanterior_spResult"/> to convert.</param>
        public static getobtenerusuarioanterior_spResultDto ToDTO(this getobtenerusuarioanterior_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getobtenerusuarioanterior_spResultDto();

            dto.i_ApprovedUpdateUserId = entity.i_ApprovedUpdateUserId;
            dto.i_ProfessionId = entity.i_ProfessionId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getobtenerusuarioanterior_spResultDto"/> to an instance of <see cref="getobtenerusuarioanterior_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getobtenerusuarioanterior_spResult> ToEntities(this IEnumerable<getobtenerusuarioanterior_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getobtenerusuarioanterior_spResult"/> to an instance of <see cref="getobtenerusuarioanterior_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getobtenerusuarioanterior_spResultDto> ToDTOs(this IEnumerable<getobtenerusuarioanterior_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
