//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:15
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getpersonmedicalhistoryreport_spResult"/> and <see cref="getpersonmedicalhistoryreport_spResultDto"/>.
    /// </summary>
    public static partial class getpersonmedicalhistoryreport_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getpersonmedicalhistoryreport_spResultDto"/> converted from <see cref="getpersonmedicalhistoryreport_spResult"/>.</param>
        static partial void OnDTO(this getpersonmedicalhistoryreport_spResult entity, getpersonmedicalhistoryreport_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getpersonmedicalhistoryreport_spResult"/> converted from <see cref="getpersonmedicalhistoryreport_spResultDto"/>.</param>
        static partial void OnEntity(this getpersonmedicalhistoryreport_spResultDto dto, getpersonmedicalhistoryreport_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getpersonmedicalhistoryreport_spResultDto"/> to an instance of <see cref="getpersonmedicalhistoryreport_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getpersonmedicalhistoryreport_spResultDto"/> to convert.</param>
        public static getpersonmedicalhistoryreport_spResult ToEntity(this getpersonmedicalhistoryreport_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getpersonmedicalhistoryreport_spResult();

            entity.i_Item = dto.i_Item;
            entity.v_PersonMedicalHistoryId = dto.v_PersonMedicalHistoryId;
            entity.v_PersonId = dto.v_PersonId;
            entity.v_DiseasesId = dto.v_DiseasesId;
            entity.v_DiseasesName = dto.v_DiseasesName;
            entity.i_TypeDiagnosticId = dto.i_TypeDiagnosticId;
            entity.d_StartDate = dto.d_StartDate;
            entity.v_TreatmentSite = dto.v_TreatmentSite;
            entity.v_GroupName = dto.v_GroupName;
            entity.v_TypeDiagnosticName = dto.v_TypeDiagnosticName;
            entity.v_DiagnosticDetail = dto.v_DiagnosticDetail;
            entity.i_Answer = dto.i_Answer;
            entity.NombreHospital = dto.NombreHospital;
            entity.v_Complicaciones = dto.v_Complicaciones;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getpersonmedicalhistoryreport_spResult"/> to an instance of <see cref="getpersonmedicalhistoryreport_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getpersonmedicalhistoryreport_spResult"/> to convert.</param>
        public static getpersonmedicalhistoryreport_spResultDto ToDTO(this getpersonmedicalhistoryreport_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getpersonmedicalhistoryreport_spResultDto();

            dto.i_Item = entity.i_Item;
            dto.v_PersonMedicalHistoryId = entity.v_PersonMedicalHistoryId;
            dto.v_PersonId = entity.v_PersonId;
            dto.v_DiseasesId = entity.v_DiseasesId;
            dto.v_DiseasesName = entity.v_DiseasesName;
            dto.i_TypeDiagnosticId = entity.i_TypeDiagnosticId;
            dto.d_StartDate = entity.d_StartDate;
            dto.v_TreatmentSite = entity.v_TreatmentSite;
            dto.v_GroupName = entity.v_GroupName;
            dto.v_TypeDiagnosticName = entity.v_TypeDiagnosticName;
            dto.v_DiagnosticDetail = entity.v_DiagnosticDetail;
            dto.i_Answer = entity.i_Answer;
            dto.NombreHospital = entity.NombreHospital;
            dto.v_Complicaciones = entity.v_Complicaciones;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getpersonmedicalhistoryreport_spResultDto"/> to an instance of <see cref="getpersonmedicalhistoryreport_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getpersonmedicalhistoryreport_spResult> ToEntities(this IEnumerable<getpersonmedicalhistoryreport_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getpersonmedicalhistoryreport_spResult"/> to an instance of <see cref="getpersonmedicalhistoryreport_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getpersonmedicalhistoryreport_spResultDto> ToDTOs(this IEnumerable<getpersonmedicalhistoryreport_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
