//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getprotocolcomponentslist_spResult"/> and <see cref="getprotocolcomponentslist_spResultDto"/>.
    /// </summary>
    public static partial class getprotocolcomponentslist_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getprotocolcomponentslist_spResultDto"/> converted from <see cref="getprotocolcomponentslist_spResult"/>.</param>
        static partial void OnDTO(this getprotocolcomponentslist_spResult entity, getprotocolcomponentslist_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getprotocolcomponentslist_spResult"/> converted from <see cref="getprotocolcomponentslist_spResultDto"/>.</param>
        static partial void OnEntity(this getprotocolcomponentslist_spResultDto dto, getprotocolcomponentslist_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getprotocolcomponentslist_spResultDto"/> to an instance of <see cref="getprotocolcomponentslist_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getprotocolcomponentslist_spResultDto"/> to convert.</param>
        public static getprotocolcomponentslist_spResult ToEntity(this getprotocolcomponentslist_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getprotocolcomponentslist_spResult();

            entity.v_ComponentId = dto.v_ComponentId;
            entity.v_ComponentName = dto.v_ComponentName;
            entity.v_Porcentajes = dto.v_Porcentajes;
            entity.v_ProtocolComponentId = dto.v_ProtocolComponentId;
            entity.r_Price = dto.r_Price;
            entity.v_Operator = dto.v_Operator;
            entity.i_Age = dto.i_Age;
            entity.v_Gender = dto.v_Gender;
            entity.i_IsConditionalIMC = dto.i_IsConditionalIMC;
            entity.r_Imc = dto.r_Imc;
            entity.v_IsConditional = dto.v_IsConditional;
            entity.i_isAdditional = dto.i_isAdditional;
            entity.v_ComponentTypeName = dto.v_ComponentTypeName;
            entity.i_RecordStatus = dto.i_RecordStatus;
            entity.i_RecordType = dto.i_RecordType;
            entity.i_GenderId = dto.i_GenderId;
            entity.i_GrupoEtarioId = dto.i_GrupoEtarioId;
            entity.i_IsConditionalId = dto.i_IsConditionalId;
            entity.i_OperatorId = dto.i_OperatorId;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.d_CreationDate = dto.d_CreationDate;
            entity.v_CategoryName = dto.v_CategoryName;
            entity.i_CategoryId = dto.i_CategoryId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getprotocolcomponentslist_spResult"/> to an instance of <see cref="getprotocolcomponentslist_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getprotocolcomponentslist_spResult"/> to convert.</param>
        public static getprotocolcomponentslist_spResultDto ToDTO(this getprotocolcomponentslist_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getprotocolcomponentslist_spResultDto();

            dto.v_ComponentId = entity.v_ComponentId;
            dto.v_ComponentName = entity.v_ComponentName;
            dto.v_Porcentajes = entity.v_Porcentajes;
            dto.v_ProtocolComponentId = entity.v_ProtocolComponentId;
            dto.r_Price = entity.r_Price;
            dto.v_Operator = entity.v_Operator;
            dto.i_Age = entity.i_Age;
            dto.v_Gender = entity.v_Gender;
            dto.i_IsConditionalIMC = entity.i_IsConditionalIMC;
            dto.r_Imc = entity.r_Imc;
            dto.v_IsConditional = entity.v_IsConditional;
            dto.i_isAdditional = entity.i_isAdditional;
            dto.v_ComponentTypeName = entity.v_ComponentTypeName;
            dto.i_RecordStatus = entity.i_RecordStatus;
            dto.i_RecordType = entity.i_RecordType;
            dto.i_GenderId = entity.i_GenderId;
            dto.i_GrupoEtarioId = entity.i_GrupoEtarioId;
            dto.i_IsConditionalId = entity.i_IsConditionalId;
            dto.i_OperatorId = entity.i_OperatorId;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.d_CreationDate = entity.d_CreationDate;
            dto.v_CategoryName = entity.v_CategoryName;
            dto.i_CategoryId = entity.i_CategoryId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getprotocolcomponentslist_spResultDto"/> to an instance of <see cref="getprotocolcomponentslist_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getprotocolcomponentslist_spResult> ToEntities(this IEnumerable<getprotocolcomponentslist_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getprotocolcomponentslist_spResult"/> to an instance of <see cref="getprotocolcomponentslist_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getprotocolcomponentslist_spResultDto> ToDTOs(this IEnumerable<getprotocolcomponentslist_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
