//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getpacient_spResult"/> and <see cref="getpacient_spResultDto"/>.
    /// </summary>
    public static partial class getpacient_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getpacient_spResultDto"/> converted from <see cref="getpacient_spResult"/>.</param>
        static partial void OnDTO(this getpacient_spResult entity, getpacient_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getpacient_spResult"/> converted from <see cref="getpacient_spResultDto"/>.</param>
        static partial void OnEntity(this getpacient_spResultDto dto, getpacient_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getpacient_spResultDto"/> to an instance of <see cref="getpacient_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getpacient_spResultDto"/> to convert.</param>
        public static getpacient_spResult ToEntity(this getpacient_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getpacient_spResult();

            entity.v_PersonId = dto.v_PersonId;
            entity.v_FirstName = dto.v_FirstName;
            entity.v_FirstLastName = dto.v_FirstLastName;
            entity.v_SecondLastName = dto.v_SecondLastName;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.v_BirthPlace = dto.v_BirthPlace;
            entity.i_MaritalStatusId = dto.i_MaritalStatusId;
            entity.i_LevelOfId = dto.i_LevelOfId;
            entity.i_DocTypeId = dto.i_DocTypeId;
            entity.i_SexTypeId = dto.i_SexTypeId;
            entity.v_TelephoneNumber = dto.v_TelephoneNumber;
            entity.v_AdressLocation = dto.v_AdressLocation;
            entity.v_Mail = dto.v_Mail;
            entity.b_Photo = dto.b_Photo;
            entity.d_Birthdate = dto.d_Birthdate;
            entity.i_BloodFactorId = dto.i_BloodFactorId;
            entity.i_BloodGroupId = dto.i_BloodGroupId;
            entity.b_FingerPrintTemplate = dto.b_FingerPrintTemplate;
            entity.b_FingerPrintImage = dto.b_FingerPrintImage;
            entity.b_RubricImage = dto.b_RubricImage;
            entity.t_RubricImageText = dto.t_RubricImageText;
            entity.v_CurrentOccupation = dto.v_CurrentOccupation;
            entity.i_DepartmentId = dto.i_DepartmentId;
            entity.i_ProvinceId = dto.i_ProvinceId;
            entity.i_DistrictId = dto.i_DistrictId;
            entity.i_ResidenceInWorkplaceId = dto.i_ResidenceInWorkplaceId;
            entity.v_ResidenceTimeInWorkplace = dto.v_ResidenceTimeInWorkplace;
            entity.i_TypeOfInsuranceId = dto.i_TypeOfInsuranceId;
            entity.i_NumberLivingChildren = dto.i_NumberLivingChildren;
            entity.i_NumberDependentChildren = dto.i_NumberDependentChildren;
            entity.i_Relationship = dto.i_Relationship;
            entity.v_ExploitedMineral = dto.v_ExploitedMineral;
            entity.i_AltitudeWorkId = dto.i_AltitudeWorkId;
            entity.i_PlaceWorkId = dto.i_PlaceWorkId;
            entity.v_OwnerName = dto.v_OwnerName;
            entity.v_NroPoliza = dto.v_NroPoliza;
            entity.v_Deducible = dto.v_Deducible;
            entity.i_NroHermanos = dto.i_NroHermanos;
            entity.i_NumberLiveChildren = dto.i_NumberLiveChildren;
            entity.i_NumberDeadChildren = dto.i_NumberDeadChildren;
            entity.v_Nacionalidad = dto.v_Nacionalidad;
            entity.v_ResidenciaAnterior = dto.v_ResidenciaAnterior;
            entity.v_Religion = dto.v_Religion;
            entity.v_ContactName = dto.v_ContactName;
            entity.v_EmergencyPhone = dto.v_EmergencyPhone;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getpacient_spResult"/> to an instance of <see cref="getpacient_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getpacient_spResult"/> to convert.</param>
        public static getpacient_spResultDto ToDTO(this getpacient_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getpacient_spResultDto();

            dto.v_PersonId = entity.v_PersonId;
            dto.v_FirstName = entity.v_FirstName;
            dto.v_FirstLastName = entity.v_FirstLastName;
            dto.v_SecondLastName = entity.v_SecondLastName;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.v_BirthPlace = entity.v_BirthPlace;
            dto.i_MaritalStatusId = entity.i_MaritalStatusId;
            dto.i_LevelOfId = entity.i_LevelOfId;
            dto.i_DocTypeId = entity.i_DocTypeId;
            dto.i_SexTypeId = entity.i_SexTypeId;
            dto.v_TelephoneNumber = entity.v_TelephoneNumber;
            dto.v_AdressLocation = entity.v_AdressLocation;
            dto.v_Mail = entity.v_Mail;
            dto.b_Photo = entity.b_Photo;
            dto.d_Birthdate = entity.d_Birthdate;
            dto.i_BloodFactorId = entity.i_BloodFactorId;
            dto.i_BloodGroupId = entity.i_BloodGroupId;
            dto.b_FingerPrintTemplate = entity.b_FingerPrintTemplate;
            dto.b_FingerPrintImage = entity.b_FingerPrintImage;
            dto.b_RubricImage = entity.b_RubricImage;
            dto.t_RubricImageText = entity.t_RubricImageText;
            dto.v_CurrentOccupation = entity.v_CurrentOccupation;
            dto.i_DepartmentId = entity.i_DepartmentId;
            dto.i_ProvinceId = entity.i_ProvinceId;
            dto.i_DistrictId = entity.i_DistrictId;
            dto.i_ResidenceInWorkplaceId = entity.i_ResidenceInWorkplaceId;
            dto.v_ResidenceTimeInWorkplace = entity.v_ResidenceTimeInWorkplace;
            dto.i_TypeOfInsuranceId = entity.i_TypeOfInsuranceId;
            dto.i_NumberLivingChildren = entity.i_NumberLivingChildren;
            dto.i_NumberDependentChildren = entity.i_NumberDependentChildren;
            dto.i_Relationship = entity.i_Relationship;
            dto.v_ExploitedMineral = entity.v_ExploitedMineral;
            dto.i_AltitudeWorkId = entity.i_AltitudeWorkId;
            dto.i_PlaceWorkId = entity.i_PlaceWorkId;
            dto.v_OwnerName = entity.v_OwnerName;
            dto.v_NroPoliza = entity.v_NroPoliza;
            dto.v_Deducible = entity.v_Deducible;
            dto.i_NroHermanos = entity.i_NroHermanos;
            dto.i_NumberLiveChildren = entity.i_NumberLiveChildren;
            dto.i_NumberDeadChildren = entity.i_NumberDeadChildren;
            dto.v_Nacionalidad = entity.v_Nacionalidad;
            dto.v_ResidenciaAnterior = entity.v_ResidenciaAnterior;
            dto.v_Religion = entity.v_Religion;
            dto.v_ContactName = entity.v_ContactName;
            dto.v_EmergencyPhone = entity.v_EmergencyPhone;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getpacient_spResultDto"/> to an instance of <see cref="getpacient_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getpacient_spResult> ToEntities(this IEnumerable<getpacient_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getpacient_spResult"/> to an instance of <see cref="getpacient_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getpacient_spResultDto> ToDTOs(this IEnumerable<getpacient_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
