//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getpacientreporteps_spResult"/> and <see cref="getpacientreporteps_spResultDto"/>.
    /// </summary>
    public static partial class getpacientreporteps_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getpacientreporteps_spResultDto"/> converted from <see cref="getpacientreporteps_spResult"/>.</param>
        static partial void OnDTO(this getpacientreporteps_spResult entity, getpacientreporteps_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getpacientreporteps_spResult"/> converted from <see cref="getpacientreporteps_spResultDto"/>.</param>
        static partial void OnEntity(this getpacientreporteps_spResultDto dto, getpacientreporteps_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getpacientreporteps_spResultDto"/> to an instance of <see cref="getpacientreporteps_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getpacientreporteps_spResultDto"/> to convert.</param>
        public static getpacientreporteps_spResult ToEntity(this getpacientreporteps_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getpacientreporteps_spResult();

            entity.empresa_ = dto.empresa_;
            entity.contrata = dto.contrata;
            entity.subcontrata = dto.subcontrata;
            entity.TimeOfDisease = dto.TimeOfDisease;
            entity.v_ObsStatusService = dto.v_ObsStatusService;
            entity.TiempoEnfermedad = dto.TiempoEnfermedad;
            entity.InicioEnfermedad = dto.InicioEnfermedad;
            entity.CursoEnfermedad = dto.CursoEnfermedad;
            entity.v_CurrentOccupation = dto.v_CurrentOccupation;
            entity.v_PersonId = dto.v_PersonId;
            entity.v_FirstName = dto.v_FirstName;
            entity.v_FirstLastName = dto.v_FirstLastName;
            entity.v_SecondLastName = dto.v_SecondLastName;
            entity.b_Photo = dto.b_Photo;
            entity.v_TypeOfInsuranceName = dto.v_TypeOfInsuranceName;
            entity.v_FullWorkingOrganizationName = dto.v_FullWorkingOrganizationName;
            entity.v_OrganitationName = dto.v_OrganitationName;
            entity.v_RelationshipName = dto.v_RelationshipName;
            entity.v_OwnerName = dto.v_OwnerName;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.d_Birthdate = dto.d_Birthdate;
            entity.i_SexTypeId = dto.i_SexTypeId;
            entity.i_DocTypeId = dto.i_DocTypeId;
            entity.i_NumberDependentChildren = dto.i_NumberDependentChildren;
            entity.i_NumberLivingChildren = dto.i_NumberLivingChildren;
            entity.FirmaTrabajador = dto.FirmaTrabajador;
            entity.HuellaTrabajador = dto.HuellaTrabajador;
            entity.v_BloodGroupName = dto.v_BloodGroupName;
            entity.v_BloodFactorName = dto.v_BloodFactorName;
            entity.v_SexTypeName = dto.v_SexTypeName;
            entity.v_TipoExamen = dto.v_TipoExamen;
            entity.v_NombreProtocolo = dto.v_NombreProtocolo;
            entity.i_EsoTypeId = dto.i_EsoTypeId;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.v_IdService = dto.v_IdService;
            entity.v_ExploitedMineral = dto.v_ExploitedMineral;
            entity.v_Story = dto.v_Story;
            entity.v_MainSymptom = dto.v_MainSymptom;
            entity.FirmaDoctor = dto.FirmaDoctor;
            entity.v_ExaAuxResult = dto.v_ExaAuxResult;
            entity.FirmaDoctorAuditor = dto.FirmaDoctorAuditor;
            entity.GESO = dto.GESO;
            entity.i_AptitudeStatusId = dto.i_AptitudeStatusId;
            entity.v_MaritalStatus = dto.v_MaritalStatus;
            entity.EmpresaClienteId = dto.EmpresaClienteId;
            entity.logoCliente = dto.logoCliente;
            entity.v_OwnerOrganizationName = dto.v_OwnerOrganizationName;
            entity.v_DoctorPhysicalExamName = dto.v_DoctorPhysicalExamName;
            entity.i_Age = dto.i_Age;
            entity.RUCEmpresa = dto.RUCEmpresa;
            entity.SedeEmpresa = dto.SedeEmpresa;
            entity.RUCcontrata = dto.RUCcontrata;
            entity.SedeContrara = dto.SedeContrara;
            entity.RUCsubcontrata = dto.RUCsubcontrata;
            entity.SedeSubContrara = dto.SedeSubContrara;
            entity.TiposervicioServicio = dto.TiposervicioServicio;
            entity.Servicio = dto.Servicio;
            entity.Licencia = dto.Licencia;
            entity.ModalidadTrabajo = dto.ModalidadTrabajo;
            entity.Value1 = dto.Value1;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getpacientreporteps_spResult"/> to an instance of <see cref="getpacientreporteps_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getpacientreporteps_spResult"/> to convert.</param>
        public static getpacientreporteps_spResultDto ToDTO(this getpacientreporteps_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getpacientreporteps_spResultDto();

            dto.empresa_ = entity.empresa_;
            dto.contrata = entity.contrata;
            dto.subcontrata = entity.subcontrata;
            dto.TimeOfDisease = entity.TimeOfDisease;
            dto.v_ObsStatusService = entity.v_ObsStatusService;
            dto.TiempoEnfermedad = entity.TiempoEnfermedad;
            dto.InicioEnfermedad = entity.InicioEnfermedad;
            dto.CursoEnfermedad = entity.CursoEnfermedad;
            dto.v_CurrentOccupation = entity.v_CurrentOccupation;
            dto.v_PersonId = entity.v_PersonId;
            dto.v_FirstName = entity.v_FirstName;
            dto.v_FirstLastName = entity.v_FirstLastName;
            dto.v_SecondLastName = entity.v_SecondLastName;
            dto.b_Photo = entity.b_Photo;
            dto.v_TypeOfInsuranceName = entity.v_TypeOfInsuranceName;
            dto.v_FullWorkingOrganizationName = entity.v_FullWorkingOrganizationName;
            dto.v_OrganitationName = entity.v_OrganitationName;
            dto.v_RelationshipName = entity.v_RelationshipName;
            dto.v_OwnerName = entity.v_OwnerName;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.d_Birthdate = entity.d_Birthdate;
            dto.i_SexTypeId = entity.i_SexTypeId;
            dto.i_DocTypeId = entity.i_DocTypeId;
            dto.i_NumberDependentChildren = entity.i_NumberDependentChildren;
            dto.i_NumberLivingChildren = entity.i_NumberLivingChildren;
            dto.FirmaTrabajador = entity.FirmaTrabajador;
            dto.HuellaTrabajador = entity.HuellaTrabajador;
            dto.v_BloodGroupName = entity.v_BloodGroupName;
            dto.v_BloodFactorName = entity.v_BloodFactorName;
            dto.v_SexTypeName = entity.v_SexTypeName;
            dto.v_TipoExamen = entity.v_TipoExamen;
            dto.v_NombreProtocolo = entity.v_NombreProtocolo;
            dto.i_EsoTypeId = entity.i_EsoTypeId;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.v_IdService = entity.v_IdService;
            dto.v_ExploitedMineral = entity.v_ExploitedMineral;
            dto.v_Story = entity.v_Story;
            dto.v_MainSymptom = entity.v_MainSymptom;
            dto.FirmaDoctor = entity.FirmaDoctor;
            dto.v_ExaAuxResult = entity.v_ExaAuxResult;
            dto.FirmaDoctorAuditor = entity.FirmaDoctorAuditor;
            dto.GESO = entity.GESO;
            dto.i_AptitudeStatusId = entity.i_AptitudeStatusId;
            dto.v_MaritalStatus = entity.v_MaritalStatus;
            dto.EmpresaClienteId = entity.EmpresaClienteId;
            dto.logoCliente = entity.logoCliente;
            dto.v_OwnerOrganizationName = entity.v_OwnerOrganizationName;
            dto.v_DoctorPhysicalExamName = entity.v_DoctorPhysicalExamName;
            dto.i_Age = entity.i_Age;
            dto.RUCEmpresa = entity.RUCEmpresa;
            dto.SedeEmpresa = entity.SedeEmpresa;
            dto.RUCcontrata = entity.RUCcontrata;
            dto.SedeContrara = entity.SedeContrara;
            dto.RUCsubcontrata = entity.RUCsubcontrata;
            dto.SedeSubContrara = entity.SedeSubContrara;
            dto.TiposervicioServicio = entity.TiposervicioServicio;
            dto.Servicio = entity.Servicio;
            dto.Licencia = entity.Licencia;
            dto.ModalidadTrabajo = entity.ModalidadTrabajo;
            dto.Value1 = entity.Value1;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getpacientreporteps_spResultDto"/> to an instance of <see cref="getpacientreporteps_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getpacientreporteps_spResult> ToEntities(this IEnumerable<getpacientreporteps_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getpacientreporteps_spResult"/> to an instance of <see cref="getpacientreporteps_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getpacientreporteps_spResultDto> ToDTOs(this IEnumerable<getpacientreporteps_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
