//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getreporttestvertigo_spResult"/> and <see cref="getreporttestvertigo_spResultDto"/>.
    /// </summary>
    public static partial class getreporttestvertigo_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getreporttestvertigo_spResultDto"/> converted from <see cref="getreporttestvertigo_spResult"/>.</param>
        static partial void OnDTO(this getreporttestvertigo_spResult entity, getreporttestvertigo_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getreporttestvertigo_spResult"/> converted from <see cref="getreporttestvertigo_spResultDto"/>.</param>
        static partial void OnEntity(this getreporttestvertigo_spResultDto dto, getreporttestvertigo_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getreporttestvertigo_spResultDto"/> to an instance of <see cref="getreporttestvertigo_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getreporttestvertigo_spResultDto"/> to convert.</param>
        public static getreporttestvertigo_spResult ToEntity(this getreporttestvertigo_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getreporttestvertigo_spResult();

            entity.EmpresaCliente = dto.EmpresaCliente;
            entity.Nombres = dto.Nombres;
            entity.FechaNacimiento = dto.FechaNacimiento;
            entity.Fecha = dto.Fecha;
            entity.Firma = dto.Firma;
            entity.NombreUsuarioGraba = dto.NombreUsuarioGraba;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getreporttestvertigo_spResult"/> to an instance of <see cref="getreporttestvertigo_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getreporttestvertigo_spResult"/> to convert.</param>
        public static getreporttestvertigo_spResultDto ToDTO(this getreporttestvertigo_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getreporttestvertigo_spResultDto();

            dto.EmpresaCliente = entity.EmpresaCliente;
            dto.Nombres = entity.Nombres;
            dto.FechaNacimiento = entity.FechaNacimiento;
            dto.Fecha = entity.Fecha;
            dto.Firma = entity.Firma;
            dto.NombreUsuarioGraba = entity.NombreUsuarioGraba;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getreporttestvertigo_spResultDto"/> to an instance of <see cref="getreporttestvertigo_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getreporttestvertigo_spResult> ToEntities(this IEnumerable<getreporttestvertigo_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getreporttestvertigo_spResult"/> to an instance of <see cref="getreporttestvertigo_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getreporttestvertigo_spResultDto> ToDTOs(this IEnumerable<getreporttestvertigo_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
