//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getreportevaluacioncardiologia_spResult"/> and <see cref="getreportevaluacioncardiologia_spResultDto"/>.
    /// </summary>
    public static partial class getreportevaluacioncardiologia_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getreportevaluacioncardiologia_spResultDto"/> converted from <see cref="getreportevaluacioncardiologia_spResult"/>.</param>
        static partial void OnDTO(this getreportevaluacioncardiologia_spResult entity, getreportevaluacioncardiologia_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getreportevaluacioncardiologia_spResult"/> converted from <see cref="getreportevaluacioncardiologia_spResultDto"/>.</param>
        static partial void OnEntity(this getreportevaluacioncardiologia_spResultDto dto, getreportevaluacioncardiologia_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getreportevaluacioncardiologia_spResultDto"/> to an instance of <see cref="getreportevaluacioncardiologia_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getreportevaluacioncardiologia_spResultDto"/> to convert.</param>
        public static getreportevaluacioncardiologia_spResult ToEntity(this getreportevaluacioncardiologia_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getreportevaluacioncardiologia_spResult();

            entity.NombreTrabajador = dto.NombreTrabajador;
            entity.Fecha = dto.Fecha;
            entity.FirmaMedico = dto.FirmaMedico;
            entity.NombreUsuarioGraba = dto.NombreUsuarioGraba;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getreportevaluacioncardiologia_spResult"/> to an instance of <see cref="getreportevaluacioncardiologia_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getreportevaluacioncardiologia_spResult"/> to convert.</param>
        public static getreportevaluacioncardiologia_spResultDto ToDTO(this getreportevaluacioncardiologia_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getreportevaluacioncardiologia_spResultDto();

            dto.NombreTrabajador = entity.NombreTrabajador;
            dto.Fecha = entity.Fecha;
            dto.FirmaMedico = entity.FirmaMedico;
            dto.NombreUsuarioGraba = entity.NombreUsuarioGraba;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getreportevaluacioncardiologia_spResultDto"/> to an instance of <see cref="getreportevaluacioncardiologia_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getreportevaluacioncardiologia_spResult> ToEntities(this IEnumerable<getreportevaluacioncardiologia_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getreportevaluacioncardiologia_spResult"/> to an instance of <see cref="getreportevaluacioncardiologia_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getreportevaluacioncardiologia_spResultDto> ToDTOs(this IEnumerable<getreportevaluacioncardiologia_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
