//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:53
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getreporttamizajedermatologico_spResult"/> and <see cref="getreporttamizajedermatologico_spResultDto"/>.
    /// </summary>
    public static partial class getreporttamizajedermatologico_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getreporttamizajedermatologico_spResultDto"/> converted from <see cref="getreporttamizajedermatologico_spResult"/>.</param>
        static partial void OnDTO(this getreporttamizajedermatologico_spResult entity, getreporttamizajedermatologico_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getreporttamizajedermatologico_spResult"/> converted from <see cref="getreporttamizajedermatologico_spResultDto"/>.</param>
        static partial void OnEntity(this getreporttamizajedermatologico_spResultDto dto, getreporttamizajedermatologico_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getreporttamizajedermatologico_spResultDto"/> to an instance of <see cref="getreporttamizajedermatologico_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getreporttamizajedermatologico_spResultDto"/> to convert.</param>
        public static getreporttamizajedermatologico_spResult ToEntity(this getreporttamizajedermatologico_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getreporttamizajedermatologico_spResult();

            entity.EmpresaCliente = dto.EmpresaCliente;
            entity.Ficha = dto.Ficha;
            entity.Hc = dto.Hc;
            entity.NombreTrabajador = dto.NombreTrabajador;
            entity.Fecha = dto.Fecha;
            entity.FirmaMedico = dto.FirmaMedico;
            entity.FirmaTrabajador = dto.FirmaTrabajador;
            entity.HuellaTrabajador = dto.HuellaTrabajador;
            entity.NombreUsuarioGraba = dto.NombreUsuarioGraba;
            entity.v_OwnerOrganizationName = dto.v_OwnerOrganizationName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getreporttamizajedermatologico_spResult"/> to an instance of <see cref="getreporttamizajedermatologico_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getreporttamizajedermatologico_spResult"/> to convert.</param>
        public static getreporttamizajedermatologico_spResultDto ToDTO(this getreporttamizajedermatologico_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getreporttamizajedermatologico_spResultDto();

            dto.EmpresaCliente = entity.EmpresaCliente;
            dto.Ficha = entity.Ficha;
            dto.Hc = entity.Hc;
            dto.NombreTrabajador = entity.NombreTrabajador;
            dto.Fecha = entity.Fecha;
            dto.FirmaMedico = entity.FirmaMedico;
            dto.FirmaTrabajador = entity.FirmaTrabajador;
            dto.HuellaTrabajador = entity.HuellaTrabajador;
            dto.NombreUsuarioGraba = entity.NombreUsuarioGraba;
            dto.v_OwnerOrganizationName = entity.v_OwnerOrganizationName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getreporttamizajedermatologico_spResultDto"/> to an instance of <see cref="getreporttamizajedermatologico_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getreporttamizajedermatologico_spResult> ToEntities(this IEnumerable<getreporttamizajedermatologico_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getreporttamizajedermatologico_spResult"/> to an instance of <see cref="getreporttamizajedermatologico_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getreporttamizajedermatologico_spResultDto> ToDTOs(this IEnumerable<getreporttamizajedermatologico_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
