//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getreportevaneurologica_spResult"/> and <see cref="getreportevaneurologica_spResultDto"/>.
    /// </summary>
    public static partial class getreportevaneurologica_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getreportevaneurologica_spResultDto"/> converted from <see cref="getreportevaneurologica_spResult"/>.</param>
        static partial void OnDTO(this getreportevaneurologica_spResult entity, getreportevaneurologica_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getreportevaneurologica_spResult"/> converted from <see cref="getreportevaneurologica_spResultDto"/>.</param>
        static partial void OnEntity(this getreportevaneurologica_spResultDto dto, getreportevaneurologica_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getreportevaneurologica_spResultDto"/> to an instance of <see cref="getreportevaneurologica_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getreportevaneurologica_spResultDto"/> to convert.</param>
        public static getreportevaneurologica_spResult ToEntity(this getreportevaneurologica_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getreportevaneurologica_spResult();

            entity.Paciente = dto.Paciente;
            entity.FechaNacimiento = dto.FechaNacimiento;
            entity.Genero = dto.Genero;
            entity.FechaServicio = dto.FechaServicio;
            entity.DNI = dto.DNI;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.FirmaMedico = dto.FirmaMedico;
            entity.Empresa = dto.Empresa;
            entity.NombreUsuarioGraba = dto.NombreUsuarioGraba;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getreportevaneurologica_spResult"/> to an instance of <see cref="getreportevaneurologica_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getreportevaneurologica_spResult"/> to convert.</param>
        public static getreportevaneurologica_spResultDto ToDTO(this getreportevaneurologica_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getreportevaneurologica_spResultDto();

            dto.Paciente = entity.Paciente;
            dto.FechaNacimiento = entity.FechaNacimiento;
            dto.Genero = entity.Genero;
            dto.FechaServicio = entity.FechaServicio;
            dto.DNI = entity.DNI;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.FirmaMedico = entity.FirmaMedico;
            dto.Empresa = entity.Empresa;
            dto.NombreUsuarioGraba = entity.NombreUsuarioGraba;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getreportevaneurologica_spResultDto"/> to an instance of <see cref="getreportevaneurologica_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getreportevaneurologica_spResult> ToEntities(this IEnumerable<getreportevaneurologica_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getreportevaneurologica_spResult"/> to an instance of <see cref="getreportevaneurologica_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getreportevaneurologica_spResultDto> ToDTOs(this IEnumerable<getreportevaneurologica_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
