//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getrecommendationbyserviceidandcomponent_spResult"/> and <see cref="getrecommendationbyserviceidandcomponent_spResultDto"/>.
    /// </summary>
    public static partial class getrecommendationbyserviceidandcomponent_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getrecommendationbyserviceidandcomponent_spResultDto"/> converted from <see cref="getrecommendationbyserviceidandcomponent_spResult"/>.</param>
        static partial void OnDTO(this getrecommendationbyserviceidandcomponent_spResult entity, getrecommendationbyserviceidandcomponent_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getrecommendationbyserviceidandcomponent_spResult"/> converted from <see cref="getrecommendationbyserviceidandcomponent_spResultDto"/>.</param>
        static partial void OnEntity(this getrecommendationbyserviceidandcomponent_spResultDto dto, getrecommendationbyserviceidandcomponent_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getrecommendationbyserviceidandcomponent_spResultDto"/> to an instance of <see cref="getrecommendationbyserviceidandcomponent_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getrecommendationbyserviceidandcomponent_spResultDto"/> to convert.</param>
        public static getrecommendationbyserviceidandcomponent_spResult ToEntity(this getrecommendationbyserviceidandcomponent_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getrecommendationbyserviceidandcomponent_spResult();

            entity.v_Recommendation = dto.v_Recommendation;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getrecommendationbyserviceidandcomponent_spResult"/> to an instance of <see cref="getrecommendationbyserviceidandcomponent_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getrecommendationbyserviceidandcomponent_spResult"/> to convert.</param>
        public static getrecommendationbyserviceidandcomponent_spResultDto ToDTO(this getrecommendationbyserviceidandcomponent_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getrecommendationbyserviceidandcomponent_spResultDto();

            dto.v_Recommendation = entity.v_Recommendation;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getrecommendationbyserviceidandcomponent_spResultDto"/> to an instance of <see cref="getrecommendationbyserviceidandcomponent_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getrecommendationbyserviceidandcomponent_spResult> ToEntities(this IEnumerable<getrecommendationbyserviceidandcomponent_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getrecommendationbyserviceidandcomponent_spResult"/> to an instance of <see cref="getrecommendationbyserviceidandcomponent_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getrecommendationbyserviceidandcomponent_spResultDto> ToDTOs(this IEnumerable<getrecommendationbyserviceidandcomponent_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
