//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getrecomendationbyserviceidandcomponentconcatec_spResult"/> and <see cref="getrecomendationbyserviceidandcomponentconcatec_spResultDto"/>.
    /// </summary>
    public static partial class getrecomendationbyserviceidandcomponentconcatec_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getrecomendationbyserviceidandcomponentconcatec_spResultDto"/> converted from <see cref="getrecomendationbyserviceidandcomponentconcatec_spResult"/>.</param>
        static partial void OnDTO(this getrecomendationbyserviceidandcomponentconcatec_spResult entity, getrecomendationbyserviceidandcomponentconcatec_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getrecomendationbyserviceidandcomponentconcatec_spResult"/> converted from <see cref="getrecomendationbyserviceidandcomponentconcatec_spResultDto"/>.</param>
        static partial void OnEntity(this getrecomendationbyserviceidandcomponentconcatec_spResultDto dto, getrecomendationbyserviceidandcomponentconcatec_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getrecomendationbyserviceidandcomponentconcatec_spResultDto"/> to an instance of <see cref="getrecomendationbyserviceidandcomponentconcatec_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getrecomendationbyserviceidandcomponentconcatec_spResultDto"/> to convert.</param>
        public static getrecomendationbyserviceidandcomponentconcatec_spResult ToEntity(this getrecomendationbyserviceidandcomponentconcatec_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getrecomendationbyserviceidandcomponentconcatec_spResult();

            entity.Recomendations = dto.Recomendations;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getrecomendationbyserviceidandcomponentconcatec_spResult"/> to an instance of <see cref="getrecomendationbyserviceidandcomponentconcatec_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getrecomendationbyserviceidandcomponentconcatec_spResult"/> to convert.</param>
        public static getrecomendationbyserviceidandcomponentconcatec_spResultDto ToDTO(this getrecomendationbyserviceidandcomponentconcatec_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getrecomendationbyserviceidandcomponentconcatec_spResultDto();

            dto.Recomendations = entity.Recomendations;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getrecomendationbyserviceidandcomponentconcatec_spResultDto"/> to an instance of <see cref="getrecomendationbyserviceidandcomponentconcatec_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getrecomendationbyserviceidandcomponentconcatec_spResult> ToEntities(this IEnumerable<getrecomendationbyserviceidandcomponentconcatec_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getrecomendationbyserviceidandcomponentconcatec_spResult"/> to an instance of <see cref="getrecomendationbyserviceidandcomponentconcatec_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getrecomendationbyserviceidandcomponentconcatec_spResultDto> ToDTOs(this IEnumerable<getrecomendationbyserviceidandcomponentconcatec_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
