//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:33:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getreportevaosteosanmartin_spResult"/> and <see cref="getreportevaosteosanmartin_spResultDto"/>.
    /// </summary>
    public static partial class getreportevaosteosanmartin_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getreportevaosteosanmartin_spResultDto"/> converted from <see cref="getreportevaosteosanmartin_spResult"/>.</param>
        static partial void OnDTO(this getreportevaosteosanmartin_spResult entity, getreportevaosteosanmartin_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getreportevaosteosanmartin_spResult"/> converted from <see cref="getreportevaosteosanmartin_spResultDto"/>.</param>
        static partial void OnEntity(this getreportevaosteosanmartin_spResultDto dto, getreportevaosteosanmartin_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getreportevaosteosanmartin_spResultDto"/> to an instance of <see cref="getreportevaosteosanmartin_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getreportevaosteosanmartin_spResultDto"/> to convert.</param>
        public static getreportevaosteosanmartin_spResult ToEntity(this getreportevaosteosanmartin_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getreportevaosteosanmartin_spResult();

            entity.Trabajador = dto.Trabajador;
            entity.FechaServicio = dto.FechaServicio;
            entity.FirmaDoctor = dto.FirmaDoctor;
            entity.NombreUsuarioGraba = dto.NombreUsuarioGraba;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getreportevaosteosanmartin_spResult"/> to an instance of <see cref="getreportevaosteosanmartin_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getreportevaosteosanmartin_spResult"/> to convert.</param>
        public static getreportevaosteosanmartin_spResultDto ToDTO(this getreportevaosteosanmartin_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getreportevaosteosanmartin_spResultDto();

            dto.Trabajador = entity.Trabajador;
            dto.FechaServicio = entity.FechaServicio;
            dto.FirmaDoctor = entity.FirmaDoctor;
            dto.NombreUsuarioGraba = entity.NombreUsuarioGraba;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getreportevaosteosanmartin_spResultDto"/> to an instance of <see cref="getreportevaosteosanmartin_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getreportevaosteosanmartin_spResult> ToEntities(this IEnumerable<getreportevaosteosanmartin_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getreportevaosteosanmartin_spResult"/> to an instance of <see cref="getreportevaosteosanmartin_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getreportevaosteosanmartin_spResultDto> ToDTOs(this IEnumerable<getreportevaosteosanmartin_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
