//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getsystemparameterforcombo_spResult"/> and <see cref="getsystemparameterforcombo_spResultDto"/>.
    /// </summary>
    public static partial class getsystemparameterforcombo_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getsystemparameterforcombo_spResultDto"/> converted from <see cref="getsystemparameterforcombo_spResult"/>.</param>
        static partial void OnDTO(this getsystemparameterforcombo_spResult entity, getsystemparameterforcombo_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getsystemparameterforcombo_spResult"/> converted from <see cref="getsystemparameterforcombo_spResultDto"/>.</param>
        static partial void OnEntity(this getsystemparameterforcombo_spResultDto dto, getsystemparameterforcombo_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getsystemparameterforcombo_spResultDto"/> to an instance of <see cref="getsystemparameterforcombo_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getsystemparameterforcombo_spResultDto"/> to convert.</param>
        public static getsystemparameterforcombo_spResult ToEntity(this getsystemparameterforcombo_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getsystemparameterforcombo_spResult();

            entity.Id = dto.Id;
            entity.Value1 = dto.Value1;
            entity.Value2 = dto.Value2;
            entity.Field = dto.Field;
            entity.GrupoId = dto.GrupoId;
            entity.ParentId = dto.ParentId;
            entity.Value3 = dto.Value3;
            entity.Value4 = dto.Value4;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getsystemparameterforcombo_spResult"/> to an instance of <see cref="getsystemparameterforcombo_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getsystemparameterforcombo_spResult"/> to convert.</param>
        public static getsystemparameterforcombo_spResultDto ToDTO(this getsystemparameterforcombo_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getsystemparameterforcombo_spResultDto();

            dto.Id = entity.Id;
            dto.Value1 = entity.Value1;
            dto.Value2 = entity.Value2;
            dto.Field = entity.Field;
            dto.GrupoId = entity.GrupoId;
            dto.ParentId = entity.ParentId;
            dto.Value3 = entity.Value3;
            dto.Value4 = entity.Value4;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getsystemparameterforcombo_spResultDto"/> to an instance of <see cref="getsystemparameterforcombo_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getsystemparameterforcombo_spResult> ToEntities(this IEnumerable<getsystemparameterforcombo_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getsystemparameterforcombo_spResult"/> to an instance of <see cref="getsystemparameterforcombo_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getsystemparameterforcombo_spResultDto> ToDTOs(this IEnumerable<getsystemparameterforcombo_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
