//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:34:53
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getservicescovid19_spResult"/> and <see cref="getservicescovid19_spResultDto"/>.
    /// </summary>
    public static partial class getservicescovid19_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getservicescovid19_spResultDto"/> converted from <see cref="getservicescovid19_spResult"/>.</param>
        static partial void OnDTO(this getservicescovid19_spResult entity, getservicescovid19_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getservicescovid19_spResult"/> converted from <see cref="getservicescovid19_spResultDto"/>.</param>
        static partial void OnEntity(this getservicescovid19_spResultDto dto, getservicescovid19_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getservicescovid19_spResultDto"/> to an instance of <see cref="getservicescovid19_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getservicescovid19_spResultDto"/> to convert.</param>
        public static getservicescovid19_spResult ToEntity(this getservicescovid19_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getservicescovid19_spResult();

            entity.SERVICIO = dto.SERVICIO;
            entity.ID_PACIENTE = dto.ID_PACIENTE;
            entity.PACIENTE = dto.PACIENTE;
            entity.DNI = dto.DNI;
            entity.NACIMIENTO = dto.NACIMIENTO;
            entity.EDAD = dto.EDAD;
            entity.OCUPACION = dto.OCUPACION;
            entity.SEXO = dto.SEXO;
            entity.TELEFONO = dto.TELEFONO;
            entity.DIRECCION = dto.DIRECCION;
            entity.CONTACTO_EMERGENCIA = dto.CONTACTO_EMERGENCIA;
            entity.TELEFONO_EMERGENCIA = dto.TELEFONO_EMERGENCIA;
            entity.EXAMEN = dto.EXAMEN;
            entity.PRECIO = dto.PRECIO;
            entity.FECHA = dto.FECHA;
            entity.COMPROBANTE = dto.COMPROBANTE;
            entity.PROTOCOLOID = dto.PROTOCOLOID;
            entity.PROTOCOLO = dto.PROTOCOLO;
            entity.RESULTADO = dto.RESULTADO;
            entity.PRIMER_RES = dto.PRIMER_RES;
            entity.SEGUNDO_RES = dto.SEGUNDO_RES;
            entity.ATENCION = dto.ATENCION;
            entity.USUARIO = dto.USUARIO;
            entity.DEPARTAMENTO = dto.DEPARTAMENTO;
            entity.PROVINCIA = dto.PROVINCIA;
            entity.DISTRITO = dto.DISTRITO;
            entity.MINAID = dto.MINAID;
            entity.MINANAME = dto.MINANAME;
            entity.CONTRATAID = dto.CONTRATAID;
            entity.CONTRATANAME = dto.CONTRATANAME;
            entity.TERCEROID = dto.TERCEROID;
            entity.TERCERONAME = dto.TERCERONAME;
            entity.v_ServiceComponentId = dto.v_ServiceComponentId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getservicescovid19_spResult"/> to an instance of <see cref="getservicescovid19_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getservicescovid19_spResult"/> to convert.</param>
        public static getservicescovid19_spResultDto ToDTO(this getservicescovid19_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getservicescovid19_spResultDto();

            dto.SERVICIO = entity.SERVICIO;
            dto.ID_PACIENTE = entity.ID_PACIENTE;
            dto.PACIENTE = entity.PACIENTE;
            dto.DNI = entity.DNI;
            dto.NACIMIENTO = entity.NACIMIENTO;
            dto.EDAD = entity.EDAD;
            dto.OCUPACION = entity.OCUPACION;
            dto.SEXO = entity.SEXO;
            dto.TELEFONO = entity.TELEFONO;
            dto.DIRECCION = entity.DIRECCION;
            dto.CONTACTO_EMERGENCIA = entity.CONTACTO_EMERGENCIA;
            dto.TELEFONO_EMERGENCIA = entity.TELEFONO_EMERGENCIA;
            dto.EXAMEN = entity.EXAMEN;
            dto.PRECIO = entity.PRECIO;
            dto.FECHA = entity.FECHA;
            dto.COMPROBANTE = entity.COMPROBANTE;
            dto.PROTOCOLOID = entity.PROTOCOLOID;
            dto.PROTOCOLO = entity.PROTOCOLO;
            dto.RESULTADO = entity.RESULTADO;
            dto.PRIMER_RES = entity.PRIMER_RES;
            dto.SEGUNDO_RES = entity.SEGUNDO_RES;
            dto.ATENCION = entity.ATENCION;
            dto.USUARIO = entity.USUARIO;
            dto.DEPARTAMENTO = entity.DEPARTAMENTO;
            dto.PROVINCIA = entity.PROVINCIA;
            dto.DISTRITO = entity.DISTRITO;
            dto.MINAID = entity.MINAID;
            dto.MINANAME = entity.MINANAME;
            dto.CONTRATAID = entity.CONTRATAID;
            dto.CONTRATANAME = entity.CONTRATANAME;
            dto.TERCEROID = entity.TERCEROID;
            dto.TERCERONAME = entity.TERCERONAME;
            dto.v_ServiceComponentId = entity.v_ServiceComponentId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicescovid19_spResultDto"/> to an instance of <see cref="getservicescovid19_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getservicescovid19_spResult> ToEntities(this IEnumerable<getservicescovid19_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicescovid19_spResult"/> to an instance of <see cref="getservicescovid19_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getservicescovid19_spResultDto> ToDTOs(this IEnumerable<getservicescovid19_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
