//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:34:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getservicespagedandfiltered_spResult"/> and <see cref="getservicespagedandfiltered_spResultDto"/>.
    /// </summary>
    public static partial class getservicespagedandfiltered_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getservicespagedandfiltered_spResultDto"/> converted from <see cref="getservicespagedandfiltered_spResult"/>.</param>
        static partial void OnDTO(this getservicespagedandfiltered_spResult entity, getservicespagedandfiltered_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getservicespagedandfiltered_spResult"/> converted from <see cref="getservicespagedandfiltered_spResultDto"/>.</param>
        static partial void OnEntity(this getservicespagedandfiltered_spResultDto dto, getservicespagedandfiltered_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getservicespagedandfiltered_spResultDto"/> to an instance of <see cref="getservicespagedandfiltered_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getservicespagedandfiltered_spResultDto"/> to convert.</param>
        public static getservicespagedandfiltered_spResult ToEntity(this getservicespagedandfiltered_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getservicespagedandfiltered_spResult();

            entity.b_FechaEntrega = dto.b_FechaEntrega;
            entity.v_PersonId = dto.v_PersonId;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.v_Pacient = dto.v_Pacient;
            entity.v_PacientDocument = dto.v_PacientDocument;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.i_ServiceStatusId = dto.i_ServiceStatusId;
            entity.i_StatusLiquidation = dto.i_StatusLiquidation;
            entity.v_CustomerOrganizationId = dto.v_CustomerOrganizationId;
            entity.v_CustomerLocationId = dto.v_CustomerLocationId;
            entity.i_MasterServiceId = dto.i_MasterServiceId;
            entity.i_ServiceTypeId = dto.i_ServiceTypeId;
            entity.i_EsoTypeId = dto.i_EsoTypeId;
            entity.v_ProtocolId = dto.v_ProtocolId;
            entity.v_ProtocolName = dto.v_ProtocolName;
            entity.i_AptitudeStatusId = dto.i_AptitudeStatusId;
            entity.CompMinera = dto.CompMinera;
            entity.Tercero = dto.Tercero;
            entity.v_OrganizationName = dto.v_OrganizationName;
            entity.i_ServiceId = dto.i_ServiceId;
            entity.v_AptitudeStatusName = dto.v_AptitudeStatusName;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.UsuarioCrea = dto.UsuarioCrea;
            entity.TipoServicioMaster = dto.TipoServicioMaster;
            entity.TipoServicioESO = dto.TipoServicioESO;
            entity.d_BirthDate = dto.d_BirthDate;
            entity.i_Age = dto.i_Age;
            entity.TipoServicio = dto.TipoServicio;
            entity.Medico = dto.Medico;
            entity.Rx_DCM = dto.Rx_DCM;
            entity.Rx_JPG = dto.Rx_JPG;
            entity.Rx_PDF = dto.Rx_PDF;
            entity.Esp_ = dto.Esp_;
            entity.Ekg = dto.Ekg;
            entity.AltaCovid19_1 = dto.AltaCovid19_1;
            entity.AltaCovid19_2 = dto.AltaCovid19_2;
            entity.Alta = dto.Alta;
            entity.Facturacion = dto.Facturacion;
            entity.d_Birthdate = dto.d_Birthdate;
            entity.CIE_10 = dto.CIE_10;
            entity.Diagnostico = dto.Diagnostico;
            entity.v_TelephoneNumber = dto.v_TelephoneNumber;
            entity.Value1 = dto.Value1;
            entity.Value2 = dto.Value2;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getservicespagedandfiltered_spResult"/> to an instance of <see cref="getservicespagedandfiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getservicespagedandfiltered_spResult"/> to convert.</param>
        public static getservicespagedandfiltered_spResultDto ToDTO(this getservicespagedandfiltered_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getservicespagedandfiltered_spResultDto();

            dto.b_FechaEntrega = entity.b_FechaEntrega;
            dto.v_PersonId = entity.v_PersonId;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.v_Pacient = entity.v_Pacient;
            dto.v_PacientDocument = entity.v_PacientDocument;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.i_ServiceStatusId = entity.i_ServiceStatusId;
            dto.i_StatusLiquidation = entity.i_StatusLiquidation;
            dto.v_CustomerOrganizationId = entity.v_CustomerOrganizationId;
            dto.v_CustomerLocationId = entity.v_CustomerLocationId;
            dto.i_MasterServiceId = entity.i_MasterServiceId;
            dto.i_ServiceTypeId = entity.i_ServiceTypeId;
            dto.i_EsoTypeId = entity.i_EsoTypeId;
            dto.v_ProtocolId = entity.v_ProtocolId;
            dto.v_ProtocolName = entity.v_ProtocolName;
            dto.i_AptitudeStatusId = entity.i_AptitudeStatusId;
            dto.CompMinera = entity.CompMinera;
            dto.Tercero = entity.Tercero;
            dto.v_OrganizationName = entity.v_OrganizationName;
            dto.i_ServiceId = entity.i_ServiceId;
            dto.v_AptitudeStatusName = entity.v_AptitudeStatusName;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.UsuarioCrea = entity.UsuarioCrea;
            dto.TipoServicioMaster = entity.TipoServicioMaster;
            dto.TipoServicioESO = entity.TipoServicioESO;
            dto.d_BirthDate = entity.d_BirthDate;
            dto.i_Age = entity.i_Age;
            dto.TipoServicio = entity.TipoServicio;
            dto.Medico = entity.Medico;
            dto.Rx_DCM = entity.Rx_DCM;
            dto.Rx_JPG = entity.Rx_JPG;
            dto.Rx_PDF = entity.Rx_PDF;
            dto.Esp_ = entity.Esp_;
            dto.Ekg = entity.Ekg;
            dto.AltaCovid19_1 = entity.AltaCovid19_1;
            dto.AltaCovid19_2 = entity.AltaCovid19_2;
            dto.Alta = entity.Alta;
            dto.Facturacion = entity.Facturacion;
            dto.d_Birthdate = entity.d_Birthdate;
            dto.CIE_10 = entity.CIE_10;
            dto.Diagnostico = entity.Diagnostico;
            dto.v_TelephoneNumber = entity.v_TelephoneNumber;
            dto.Value1 = entity.Value1;
            dto.Value2 = entity.Value2;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicespagedandfiltered_spResultDto"/> to an instance of <see cref="getservicespagedandfiltered_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getservicespagedandfiltered_spResult> ToEntities(this IEnumerable<getservicespagedandfiltered_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicespagedandfiltered_spResult"/> to an instance of <see cref="getservicespagedandfiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getservicespagedandfiltered_spResultDto> ToDTOs(this IEnumerable<getservicespagedandfiltered_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
