//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:34:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getservicecomponentconclusionesdxserviceid_spResult"/> and <see cref="getservicecomponentconclusionesdxserviceid_spResultDto"/>.
    /// </summary>
    public static partial class getservicecomponentconclusionesdxserviceid_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getservicecomponentconclusionesdxserviceid_spResultDto"/> converted from <see cref="getservicecomponentconclusionesdxserviceid_spResult"/>.</param>
        static partial void OnDTO(this getservicecomponentconclusionesdxserviceid_spResult entity, getservicecomponentconclusionesdxserviceid_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getservicecomponentconclusionesdxserviceid_spResult"/> converted from <see cref="getservicecomponentconclusionesdxserviceid_spResultDto"/>.</param>
        static partial void OnEntity(this getservicecomponentconclusionesdxserviceid_spResultDto dto, getservicecomponentconclusionesdxserviceid_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getservicecomponentconclusionesdxserviceid_spResultDto"/> to an instance of <see cref="getservicecomponentconclusionesdxserviceid_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getservicecomponentconclusionesdxserviceid_spResultDto"/> to convert.</param>
        public static getservicecomponentconclusionesdxserviceid_spResult ToEntity(this getservicecomponentconclusionesdxserviceid_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getservicecomponentconclusionesdxserviceid_spResult();

            entity.v_DiagnosticRepositoryId = dto.v_DiagnosticRepositoryId;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.v_ComponentId = dto.v_ComponentId;
            entity.v_DiseasesId = dto.v_DiseasesId;
            entity.i_AutoManualId = dto.i_AutoManualId;
            entity.i_PreQualificationId = dto.i_PreQualificationId;
            entity.i_FinalQualificationId = dto.i_FinalQualificationId;
            entity.i_DiagnosticTypeId = dto.i_DiagnosticTypeId;
            entity.i_IsSentToAntecedent = dto.i_IsSentToAntecedent;
            entity.d_ExpirationDateDiagnostic = dto.d_ExpirationDateDiagnostic;
            entity.i_GenerateMedicalBreak = dto.i_GenerateMedicalBreak;
            entity.v_RecomendationsName = dto.v_RecomendationsName;
            entity.v_RestrictionsName = dto.v_RestrictionsName;
            entity.v_DiseasesName = dto.v_DiseasesName;
            entity.v_AutoManualName = dto.v_AutoManualName;
            entity.v_ComponentName = dto.v_ComponentName;
            entity.v_PreQualificationName = dto.v_PreQualificationName;
            entity.v_FinalQualificationName = dto.v_FinalQualificationName;
            entity.v_DiagnosticTypeName = dto.v_DiagnosticTypeName;
            entity.v_IsSentToAntecedentName = dto.v_IsSentToAntecedentName;
            entity.i_RecordStatus = dto.i_RecordStatus;
            entity.i_RecordType = dto.i_RecordType;
            entity.v_CreationUser = dto.v_CreationUser;
            entity.v_UpdateUser = dto.v_UpdateUser;
            entity.d_CreationDate = dto.d_CreationDate;
            entity.d_UpdateDate = dto.d_UpdateDate;
            entity.i_IsDeleted = dto.i_IsDeleted;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getservicecomponentconclusionesdxserviceid_spResult"/> to an instance of <see cref="getservicecomponentconclusionesdxserviceid_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getservicecomponentconclusionesdxserviceid_spResult"/> to convert.</param>
        public static getservicecomponentconclusionesdxserviceid_spResultDto ToDTO(this getservicecomponentconclusionesdxserviceid_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getservicecomponentconclusionesdxserviceid_spResultDto();

            dto.v_DiagnosticRepositoryId = entity.v_DiagnosticRepositoryId;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.v_ComponentId = entity.v_ComponentId;
            dto.v_DiseasesId = entity.v_DiseasesId;
            dto.i_AutoManualId = entity.i_AutoManualId;
            dto.i_PreQualificationId = entity.i_PreQualificationId;
            dto.i_FinalQualificationId = entity.i_FinalQualificationId;
            dto.i_DiagnosticTypeId = entity.i_DiagnosticTypeId;
            dto.i_IsSentToAntecedent = entity.i_IsSentToAntecedent;
            dto.d_ExpirationDateDiagnostic = entity.d_ExpirationDateDiagnostic;
            dto.i_GenerateMedicalBreak = entity.i_GenerateMedicalBreak;
            dto.v_RecomendationsName = entity.v_RecomendationsName;
            dto.v_RestrictionsName = entity.v_RestrictionsName;
            dto.v_DiseasesName = entity.v_DiseasesName;
            dto.v_AutoManualName = entity.v_AutoManualName;
            dto.v_ComponentName = entity.v_ComponentName;
            dto.v_PreQualificationName = entity.v_PreQualificationName;
            dto.v_FinalQualificationName = entity.v_FinalQualificationName;
            dto.v_DiagnosticTypeName = entity.v_DiagnosticTypeName;
            dto.v_IsSentToAntecedentName = entity.v_IsSentToAntecedentName;
            dto.i_RecordStatus = entity.i_RecordStatus;
            dto.i_RecordType = entity.i_RecordType;
            dto.v_CreationUser = entity.v_CreationUser;
            dto.v_UpdateUser = entity.v_UpdateUser;
            dto.d_CreationDate = entity.d_CreationDate;
            dto.d_UpdateDate = entity.d_UpdateDate;
            dto.i_IsDeleted = entity.i_IsDeleted;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicecomponentconclusionesdxserviceid_spResultDto"/> to an instance of <see cref="getservicecomponentconclusionesdxserviceid_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getservicecomponentconclusionesdxserviceid_spResult> ToEntities(this IEnumerable<getservicecomponentconclusionesdxserviceid_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicecomponentconclusionesdxserviceid_spResult"/> to an instance of <see cref="getservicecomponentconclusionesdxserviceid_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getservicecomponentconclusionesdxserviceid_spResultDto> ToDTOs(this IEnumerable<getservicecomponentconclusionesdxserviceid_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
