//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:34:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getservicereport_spResult"/> and <see cref="getservicereport_spResultDto"/>.
    /// </summary>
    public static partial class getservicereport_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getservicereport_spResultDto"/> converted from <see cref="getservicereport_spResult"/>.</param>
        static partial void OnDTO(this getservicereport_spResult entity, getservicereport_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getservicereport_spResult"/> converted from <see cref="getservicereport_spResultDto"/>.</param>
        static partial void OnEntity(this getservicereport_spResultDto dto, getservicereport_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getservicereport_spResultDto"/> to an instance of <see cref="getservicereport_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getservicereport_spResultDto"/> to convert.</param>
        public static getservicereport_spResult ToEntity(this getservicereport_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getservicereport_spResult();

            entity.v_PersonId = dto.v_PersonId;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.i_DiaV = dto.i_DiaV;
            entity.i_MesV = dto.i_MesV;
            entity.i_AnioV = dto.i_AnioV;
            entity.i_EsoTypeId = dto.i_EsoTypeId;
            entity.RUC = dto.RUC;
            entity.AreaTrabajo = dto.AreaTrabajo;
            entity.EmpresaTrabajo = dto.EmpresaTrabajo;
            entity.EmpresaEmpleadora = dto.EmpresaEmpleadora;
            entity.RubroEmpresaTrabajo = dto.RubroEmpresaTrabajo;
            entity.DireccionEmpresaTrabajo = dto.DireccionEmpresaTrabajo;
            entity.DepartamentoEmpresaTrabajo = dto.DepartamentoEmpresaTrabajo;
            entity.ProvinciaEmpresaTrabajo = dto.ProvinciaEmpresaTrabajo;
            entity.DistritoEmpresaTrabajo = dto.DistritoEmpresaTrabajo;
            entity.v_CurrentOccupation = dto.v_CurrentOccupation;
            entity.b_Logo = dto.b_Logo;
            entity.EmpresaClienteId = dto.EmpresaClienteId;
            entity.v_CustomerOrganizationId = dto.v_CustomerOrganizationId;
            entity.i_DocTypeId = dto.i_DocTypeId;
            entity.v_Pacient = dto.v_Pacient;
            entity.d_BirthDate = dto.d_BirthDate;
            entity.i_DiaN = dto.i_DiaN;
            entity.i_MesN = dto.i_MesN;
            entity.i_AnioN = dto.i_AnioN;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.v_AdressLocation = dto.v_AdressLocation;
            entity.v_EmergencyPhone = dto.v_EmergencyPhone;
            entity.v_ContactName = dto.v_ContactName;
            entity.DepartamentoPaciente = dto.DepartamentoPaciente;
            entity.ProvinciaPaciente = dto.ProvinciaPaciente;
            entity.DistritoPaciente = dto.DistritoPaciente;
            entity.i_ResidenceInWorkplaceId = dto.i_ResidenceInWorkplaceId;
            entity.v_ResidenceTimeInWorkplace = dto.v_ResidenceTimeInWorkplace;
            entity.i_TypeOfInsuranceId = dto.i_TypeOfInsuranceId;
            entity.Email = dto.Email;
            entity.Telefono = dto.Telefono;
            entity.EstadoCivil = dto.EstadoCivil;
            entity.GradoInstruccion = dto.GradoInstruccion;
            entity.v_Story = dto.v_Story;
            entity.i_AptitudeStatusId = dto.i_AptitudeStatusId;
            entity.v_GenderName = dto.v_GenderName;
            entity.HijosVivos = dto.HijosVivos;
            entity.HijosMuertos = dto.HijosMuertos;
            entity.HijosDependientes = dto.HijosDependientes;
            entity.v_BirthPlace = dto.v_BirthPlace;
            entity.i_PlaceWorkId = dto.i_PlaceWorkId;
            entity.v_ExploitedMineral = dto.v_ExploitedMineral;
            entity.i_AltitudeWorkId = dto.i_AltitudeWorkId;
            entity.i_SexTypeId = dto.i_SexTypeId;
            entity.i_MaritalStatusId = dto.i_MaritalStatusId;
            entity.i_LevelOfId = dto.i_LevelOfId;
            entity.FirmaTrabajador = dto.FirmaTrabajador;
            entity.HuellaTrabajador = dto.HuellaTrabajador;
            entity.d_GlobalExpirationDate = dto.d_GlobalExpirationDate;
            entity.FirmaDoctor = dto.FirmaDoctor;
            entity.NombreDoctor = dto.NombreDoctor;
            entity.CMP = dto.CMP;
            entity.d_Fur = dto.d_Fur;
            entity.v_CatemenialRegime = dto.v_CatemenialRegime;
            entity.i_MacId = dto.i_MacId;
            entity.v_Mac = dto.v_Mac;
            entity.d_PAP = dto.d_PAP;
            entity.d_Mamografia = dto.d_Mamografia;
            entity.v_CiruGine = dto.v_CiruGine;
            entity.v_Gestapara = dto.v_Gestapara;
            entity.v_Menarquia = dto.v_Menarquia;
            entity.v_Findings = dto.v_Findings;
            entity.v_CustomerOrganizationName = dto.v_CustomerOrganizationName;
            entity.i_NroHermanos = dto.i_NroHermanos;
            entity.Value5 = dto.Value5;
            entity.Value2 = dto.Value2;
            entity.Value3 = dto.Value3;
            entity.v_OwnerOrganizationName = dto.v_OwnerOrganizationName;
            entity.i_HasSymptomId = dto.i_HasSymptomId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getservicereport_spResult"/> to an instance of <see cref="getservicereport_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getservicereport_spResult"/> to convert.</param>
        public static getservicereport_spResultDto ToDTO(this getservicereport_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getservicereport_spResultDto();

            dto.v_PersonId = entity.v_PersonId;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.i_DiaV = entity.i_DiaV;
            dto.i_MesV = entity.i_MesV;
            dto.i_AnioV = entity.i_AnioV;
            dto.i_EsoTypeId = entity.i_EsoTypeId;
            dto.RUC = entity.RUC;
            dto.AreaTrabajo = entity.AreaTrabajo;
            dto.EmpresaTrabajo = entity.EmpresaTrabajo;
            dto.EmpresaEmpleadora = entity.EmpresaEmpleadora;
            dto.RubroEmpresaTrabajo = entity.RubroEmpresaTrabajo;
            dto.DireccionEmpresaTrabajo = entity.DireccionEmpresaTrabajo;
            dto.DepartamentoEmpresaTrabajo = entity.DepartamentoEmpresaTrabajo;
            dto.ProvinciaEmpresaTrabajo = entity.ProvinciaEmpresaTrabajo;
            dto.DistritoEmpresaTrabajo = entity.DistritoEmpresaTrabajo;
            dto.v_CurrentOccupation = entity.v_CurrentOccupation;
            dto.b_Logo = entity.b_Logo;
            dto.EmpresaClienteId = entity.EmpresaClienteId;
            dto.v_CustomerOrganizationId = entity.v_CustomerOrganizationId;
            dto.i_DocTypeId = entity.i_DocTypeId;
            dto.v_Pacient = entity.v_Pacient;
            dto.d_BirthDate = entity.d_BirthDate;
            dto.i_DiaN = entity.i_DiaN;
            dto.i_MesN = entity.i_MesN;
            dto.i_AnioN = entity.i_AnioN;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.v_AdressLocation = entity.v_AdressLocation;
            dto.v_EmergencyPhone = entity.v_EmergencyPhone;
            dto.v_ContactName = entity.v_ContactName;
            dto.DepartamentoPaciente = entity.DepartamentoPaciente;
            dto.ProvinciaPaciente = entity.ProvinciaPaciente;
            dto.DistritoPaciente = entity.DistritoPaciente;
            dto.i_ResidenceInWorkplaceId = entity.i_ResidenceInWorkplaceId;
            dto.v_ResidenceTimeInWorkplace = entity.v_ResidenceTimeInWorkplace;
            dto.i_TypeOfInsuranceId = entity.i_TypeOfInsuranceId;
            dto.Email = entity.Email;
            dto.Telefono = entity.Telefono;
            dto.EstadoCivil = entity.EstadoCivil;
            dto.GradoInstruccion = entity.GradoInstruccion;
            dto.v_Story = entity.v_Story;
            dto.i_AptitudeStatusId = entity.i_AptitudeStatusId;
            dto.v_GenderName = entity.v_GenderName;
            dto.HijosVivos = entity.HijosVivos;
            dto.HijosMuertos = entity.HijosMuertos;
            dto.HijosDependientes = entity.HijosDependientes;
            dto.v_BirthPlace = entity.v_BirthPlace;
            dto.i_PlaceWorkId = entity.i_PlaceWorkId;
            dto.v_ExploitedMineral = entity.v_ExploitedMineral;
            dto.i_AltitudeWorkId = entity.i_AltitudeWorkId;
            dto.i_SexTypeId = entity.i_SexTypeId;
            dto.i_MaritalStatusId = entity.i_MaritalStatusId;
            dto.i_LevelOfId = entity.i_LevelOfId;
            dto.FirmaTrabajador = entity.FirmaTrabajador;
            dto.HuellaTrabajador = entity.HuellaTrabajador;
            dto.d_GlobalExpirationDate = entity.d_GlobalExpirationDate;
            dto.FirmaDoctor = entity.FirmaDoctor;
            dto.NombreDoctor = entity.NombreDoctor;
            dto.CMP = entity.CMP;
            dto.d_Fur = entity.d_Fur;
            dto.v_CatemenialRegime = entity.v_CatemenialRegime;
            dto.i_MacId = entity.i_MacId;
            dto.v_Mac = entity.v_Mac;
            dto.d_PAP = entity.d_PAP;
            dto.d_Mamografia = entity.d_Mamografia;
            dto.v_CiruGine = entity.v_CiruGine;
            dto.v_Gestapara = entity.v_Gestapara;
            dto.v_Menarquia = entity.v_Menarquia;
            dto.v_Findings = entity.v_Findings;
            dto.v_CustomerOrganizationName = entity.v_CustomerOrganizationName;
            dto.i_NroHermanos = entity.i_NroHermanos;
            dto.Value5 = entity.Value5;
            dto.Value2 = entity.Value2;
            dto.Value3 = entity.Value3;
            dto.v_OwnerOrganizationName = entity.v_OwnerOrganizationName;
            dto.i_HasSymptomId = entity.i_HasSymptomId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicereport_spResultDto"/> to an instance of <see cref="getservicereport_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getservicereport_spResult> ToEntities(this IEnumerable<getservicereport_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicereport_spResult"/> to an instance of <see cref="getservicereport_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getservicereport_spResultDto> ToDTOs(this IEnumerable<getservicereport_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
