//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:34:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getservicecomponentfields2_spResult"/> and <see cref="getservicecomponentfields2_spResultDto"/>.
    /// </summary>
    public static partial class getservicecomponentfields2_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getservicecomponentfields2_spResultDto"/> converted from <see cref="getservicecomponentfields2_spResult"/>.</param>
        static partial void OnDTO(this getservicecomponentfields2_spResult entity, getservicecomponentfields2_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getservicecomponentfields2_spResult"/> converted from <see cref="getservicecomponentfields2_spResultDto"/>.</param>
        static partial void OnEntity(this getservicecomponentfields2_spResultDto dto, getservicecomponentfields2_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getservicecomponentfields2_spResultDto"/> to an instance of <see cref="getservicecomponentfields2_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getservicecomponentfields2_spResultDto"/> to convert.</param>
        public static getservicecomponentfields2_spResult ToEntity(this getservicecomponentfields2_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getservicecomponentfields2_spResult();

            entity.v_ServiceComponentFieldsId = dto.v_ServiceComponentFieldsId;
            entity.v_ComponentFieldsId = dto.v_ComponentFieldsId;
            entity.v_ServiceComponentId = dto.v_ServiceComponentId;
            entity.i_HasAutomaticDxId = dto.i_HasAutomaticDxId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getservicecomponentfields2_spResult"/> to an instance of <see cref="getservicecomponentfields2_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getservicecomponentfields2_spResult"/> to convert.</param>
        public static getservicecomponentfields2_spResultDto ToDTO(this getservicecomponentfields2_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getservicecomponentfields2_spResultDto();

            dto.v_ServiceComponentFieldsId = entity.v_ServiceComponentFieldsId;
            dto.v_ComponentFieldsId = entity.v_ComponentFieldsId;
            dto.v_ServiceComponentId = entity.v_ServiceComponentId;
            dto.i_HasAutomaticDxId = entity.i_HasAutomaticDxId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicecomponentfields2_spResultDto"/> to an instance of <see cref="getservicecomponentfields2_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getservicecomponentfields2_spResult> ToEntities(this IEnumerable<getservicecomponentfields2_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicecomponentfields2_spResult"/> to an instance of <see cref="getservicecomponentfields2_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getservicecomponentfields2_spResultDto> ToDTOs(this IEnumerable<getservicecomponentfields2_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
