//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:34:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getselectedindexchanged_spResult"/> and <see cref="getselectedindexchanged_spResultDto"/>.
    /// </summary>
    public static partial class getselectedindexchanged_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getselectedindexchanged_spResultDto"/> converted from <see cref="getselectedindexchanged_spResult"/>.</param>
        static partial void OnDTO(this getselectedindexchanged_spResult entity, getselectedindexchanged_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getselectedindexchanged_spResult"/> converted from <see cref="getselectedindexchanged_spResultDto"/>.</param>
        static partial void OnEntity(this getselectedindexchanged_spResultDto dto, getselectedindexchanged_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getselectedindexchanged_spResultDto"/> to an instance of <see cref="getselectedindexchanged_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getselectedindexchanged_spResultDto"/> to convert.</param>
        public static getselectedindexchanged_spResult ToEntity(this getselectedindexchanged_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getselectedindexchanged_spResult();

            entity.i_UpdateUserOccupationalMedicaltId = dto.i_UpdateUserOccupationalMedicaltId;
            entity.v_UserName = dto.v_UserName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getselectedindexchanged_spResult"/> to an instance of <see cref="getselectedindexchanged_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getselectedindexchanged_spResult"/> to convert.</param>
        public static getselectedindexchanged_spResultDto ToDTO(this getselectedindexchanged_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getselectedindexchanged_spResultDto();

            dto.i_UpdateUserOccupationalMedicaltId = entity.i_UpdateUserOccupationalMedicaltId;
            dto.v_UserName = entity.v_UserName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getselectedindexchanged_spResultDto"/> to an instance of <see cref="getselectedindexchanged_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getselectedindexchanged_spResult> ToEntities(this IEnumerable<getselectedindexchanged_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getselectedindexchanged_spResult"/> to an instance of <see cref="getselectedindexchanged_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getselectedindexchanged_spResultDto> ToDTOs(this IEnumerable<getselectedindexchanged_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
