//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getsystemuserResult"/> and <see cref="getsystemuserResultDto"/>.
    /// </summary>
    public static partial class getsystemuserResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getsystemuserResultDto"/> converted from <see cref="getsystemuserResult"/>.</param>
        static partial void OnDTO(this getsystemuserResult entity, getsystemuserResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getsystemuserResult"/> converted from <see cref="getsystemuserResultDto"/>.</param>
        static partial void OnEntity(this getsystemuserResultDto dto, getsystemuserResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getsystemuserResultDto"/> to an instance of <see cref="getsystemuserResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getsystemuserResultDto"/> to convert.</param>
        public static getsystemuserResult ToEntity(this getsystemuserResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getsystemuserResult();

            entity.v_UserName = dto.v_UserName;
            entity.i_SystemUserTypeId = dto.i_SystemUserTypeId;
            entity.v_Password = dto.v_Password;
            entity.v_PersonId = dto.v_PersonId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getsystemuserResult"/> to an instance of <see cref="getsystemuserResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getsystemuserResult"/> to convert.</param>
        public static getsystemuserResultDto ToDTO(this getsystemuserResult entity)
        {
            if (entity == null) return null;

            var dto = new getsystemuserResultDto();

            dto.v_UserName = entity.v_UserName;
            dto.i_SystemUserTypeId = entity.i_SystemUserTypeId;
            dto.v_Password = entity.v_Password;
            dto.v_PersonId = entity.v_PersonId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getsystemuserResultDto"/> to an instance of <see cref="getsystemuserResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getsystemuserResult> ToEntities(this IEnumerable<getsystemuserResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getsystemuserResult"/> to an instance of <see cref="getsystemuserResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getsystemuserResultDto> ToDTOs(this IEnumerable<getsystemuserResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
