//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getsintomascovid19_spResult"/> and <see cref="getsintomascovid19_spResultDto"/>.
    /// </summary>
    public static partial class getsintomascovid19_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getsintomascovid19_spResultDto"/> converted from <see cref="getsintomascovid19_spResult"/>.</param>
        static partial void OnDTO(this getsintomascovid19_spResult entity, getsintomascovid19_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getsintomascovid19_spResult"/> converted from <see cref="getsintomascovid19_spResultDto"/>.</param>
        static partial void OnEntity(this getsintomascovid19_spResultDto dto, getsintomascovid19_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getsintomascovid19_spResultDto"/> to an instance of <see cref="getsintomascovid19_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getsintomascovid19_spResultDto"/> to convert.</param>
        public static getsintomascovid19_spResult ToEntity(this getsintomascovid19_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getsintomascovid19_spResult();

            entity.v_TextLabel = dto.v_TextLabel;
            entity.v_Value1 = dto.v_Value1;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getsintomascovid19_spResult"/> to an instance of <see cref="getsintomascovid19_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getsintomascovid19_spResult"/> to convert.</param>
        public static getsintomascovid19_spResultDto ToDTO(this getsintomascovid19_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getsintomascovid19_spResultDto();

            dto.v_TextLabel = entity.v_TextLabel;
            dto.v_Value1 = entity.v_Value1;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getsintomascovid19_spResultDto"/> to an instance of <see cref="getsintomascovid19_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getsintomascovid19_spResult> ToEntities(this IEnumerable<getsintomascovid19_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getsintomascovid19_spResult"/> to an instance of <see cref="getsintomascovid19_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getsintomascovid19_spResultDto> ToDTOs(this IEnumerable<getsintomascovid19_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
