//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:34:17
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getservicecomponentsinfo_spResult"/> and <see cref="getservicecomponentsinfo_spResultDto"/>.
    /// </summary>
    public static partial class getservicecomponentsinfo_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getservicecomponentsinfo_spResultDto"/> converted from <see cref="getservicecomponentsinfo_spResult"/>.</param>
        static partial void OnDTO(this getservicecomponentsinfo_spResult entity, getservicecomponentsinfo_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getservicecomponentsinfo_spResult"/> converted from <see cref="getservicecomponentsinfo_spResultDto"/>.</param>
        static partial void OnEntity(this getservicecomponentsinfo_spResultDto dto, getservicecomponentsinfo_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getservicecomponentsinfo_spResultDto"/> to an instance of <see cref="getservicecomponentsinfo_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getservicecomponentsinfo_spResultDto"/> to convert.</param>
        public static getservicecomponentsinfo_spResult ToEntity(this getservicecomponentsinfo_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getservicecomponentsinfo_spResult();

            entity.v_ServiceComponentId = dto.v_ServiceComponentId;
            entity.v_ComponentId = dto.v_ComponentId;
            entity.v_ComponentName = dto.v_ComponentName;
            entity.i_ServiceComponentStatusId = dto.i_ServiceComponentStatusId;
            entity.v_ServiceComponentStatusName = dto.v_ServiceComponentStatusName;
            entity.v_Comment = dto.v_Comment;
            entity.i_ExternalInternalId = dto.i_ExternalInternalId;
            entity.d_StartDate = dto.d_StartDate;
            entity.d_EndDate = dto.d_EndDate;
            entity.i_QueueStatusId = dto.i_QueueStatusId;
            entity.v_CreationUser = dto.v_CreationUser;
            entity.v_UpdateUser = dto.v_UpdateUser;
            entity.d_CreationDate = dto.d_CreationDate;
            entity.d_UpdateDate = dto.d_UpdateDate;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.i_ControlId = dto.i_ControlId;
            entity.i_IsApprovedId = dto.i_IsApprovedId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getservicecomponentsinfo_spResult"/> to an instance of <see cref="getservicecomponentsinfo_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getservicecomponentsinfo_spResult"/> to convert.</param>
        public static getservicecomponentsinfo_spResultDto ToDTO(this getservicecomponentsinfo_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getservicecomponentsinfo_spResultDto();

            dto.v_ServiceComponentId = entity.v_ServiceComponentId;
            dto.v_ComponentId = entity.v_ComponentId;
            dto.v_ComponentName = entity.v_ComponentName;
            dto.i_ServiceComponentStatusId = entity.i_ServiceComponentStatusId;
            dto.v_ServiceComponentStatusName = entity.v_ServiceComponentStatusName;
            dto.v_Comment = entity.v_Comment;
            dto.i_ExternalInternalId = entity.i_ExternalInternalId;
            dto.d_StartDate = entity.d_StartDate;
            dto.d_EndDate = entity.d_EndDate;
            dto.i_QueueStatusId = entity.i_QueueStatusId;
            dto.v_CreationUser = entity.v_CreationUser;
            dto.v_UpdateUser = entity.v_UpdateUser;
            dto.d_CreationDate = entity.d_CreationDate;
            dto.d_UpdateDate = entity.d_UpdateDate;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.i_ControlId = entity.i_ControlId;
            dto.i_IsApprovedId = entity.i_IsApprovedId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicecomponentsinfo_spResultDto"/> to an instance of <see cref="getservicecomponentsinfo_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getservicecomponentsinfo_spResult> ToEntities(this IEnumerable<getservicecomponentsinfo_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getservicecomponentsinfo_spResult"/> to an instance of <see cref="getservicecomponentsinfo_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getservicecomponentsinfo_spResultDto> ToDTOs(this IEnumerable<getservicecomponentsinfo_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
