//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:18
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="gettypeofeeppagedandfiltered_spResult"/> and <see cref="gettypeofeeppagedandfiltered_spResultDto"/>.
    /// </summary>
    public static partial class gettypeofeeppagedandfiltered_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="gettypeofeeppagedandfiltered_spResultDto"/> converted from <see cref="gettypeofeeppagedandfiltered_spResult"/>.</param>
        static partial void OnDTO(this gettypeofeeppagedandfiltered_spResult entity, gettypeofeeppagedandfiltered_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="gettypeofeeppagedandfiltered_spResult"/> converted from <see cref="gettypeofeeppagedandfiltered_spResultDto"/>.</param>
        static partial void OnEntity(this gettypeofeeppagedandfiltered_spResultDto dto, gettypeofeeppagedandfiltered_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="gettypeofeeppagedandfiltered_spResultDto"/> to an instance of <see cref="gettypeofeeppagedandfiltered_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="gettypeofeeppagedandfiltered_spResultDto"/> to convert.</param>
        public static gettypeofeeppagedandfiltered_spResult ToEntity(this gettypeofeeppagedandfiltered_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new gettypeofeeppagedandfiltered_spResult();

            entity.v_TypeofEEPId = dto.v_TypeofEEPId;
            entity.v_TypeofEEPName = dto.v_TypeofEEPName;
            entity.i_TypeofEEPId = dto.i_TypeofEEPId;
            entity.r_Percentage = dto.r_Percentage;
            entity.i_RecordStatus = dto.i_RecordStatus;
            entity.i_RecordType = dto.i_RecordType;
            entity.v_CreationUser = dto.v_CreationUser;
            entity.v_UpdateUser = dto.v_UpdateUser;
            entity.d_CreationDate = dto.d_CreationDate;
            entity.d_UpdateDate = dto.d_UpdateDate;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="gettypeofeeppagedandfiltered_spResult"/> to an instance of <see cref="gettypeofeeppagedandfiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="gettypeofeeppagedandfiltered_spResult"/> to convert.</param>
        public static gettypeofeeppagedandfiltered_spResultDto ToDTO(this gettypeofeeppagedandfiltered_spResult entity)
        {
            if (entity == null) return null;

            var dto = new gettypeofeeppagedandfiltered_spResultDto();

            dto.v_TypeofEEPId = entity.v_TypeofEEPId;
            dto.v_TypeofEEPName = entity.v_TypeofEEPName;
            dto.i_TypeofEEPId = entity.i_TypeofEEPId;
            dto.r_Percentage = entity.r_Percentage;
            dto.i_RecordStatus = entity.i_RecordStatus;
            dto.i_RecordType = entity.i_RecordType;
            dto.v_CreationUser = entity.v_CreationUser;
            dto.v_UpdateUser = entity.v_UpdateUser;
            dto.d_CreationDate = entity.d_CreationDate;
            dto.d_UpdateDate = entity.d_UpdateDate;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="gettypeofeeppagedandfiltered_spResultDto"/> to an instance of <see cref="gettypeofeeppagedandfiltered_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<gettypeofeeppagedandfiltered_spResult> ToEntities(this IEnumerable<gettypeofeeppagedandfiltered_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="gettypeofeeppagedandfiltered_spResult"/> to an instance of <see cref="gettypeofeeppagedandfiltered_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<gettypeofeeppagedandfiltered_spResultDto> ToDTOs(this IEnumerable<gettypeofeeppagedandfiltered_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
