//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getvaloresexamencomponete_spResult"/> and <see cref="getvaloresexamencomponete_spResultDto"/>.
    /// </summary>
    public static partial class getvaloresexamencomponete_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getvaloresexamencomponete_spResultDto"/> converted from <see cref="getvaloresexamencomponete_spResult"/>.</param>
        static partial void OnDTO(this getvaloresexamencomponete_spResult entity, getvaloresexamencomponete_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getvaloresexamencomponete_spResult"/> converted from <see cref="getvaloresexamencomponete_spResultDto"/>.</param>
        static partial void OnEntity(this getvaloresexamencomponete_spResultDto dto, getvaloresexamencomponete_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getvaloresexamencomponete_spResultDto"/> to an instance of <see cref="getvaloresexamencomponete_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getvaloresexamencomponete_spResultDto"/> to convert.</param>
        public static getvaloresexamencomponete_spResult ToEntity(this getvaloresexamencomponete_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getvaloresexamencomponete_spResult();

            entity.v_ComponentFieldId = dto.v_ComponentFieldId;
            entity.v_ComponentFielName = dto.v_ComponentFielName;
            entity.v_ServiceComponentFieldsId = dto.v_ServiceComponentFieldsId;
            entity.v_Value1 = dto.v_Value1;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getvaloresexamencomponete_spResult"/> to an instance of <see cref="getvaloresexamencomponete_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getvaloresexamencomponete_spResult"/> to convert.</param>
        public static getvaloresexamencomponete_spResultDto ToDTO(this getvaloresexamencomponete_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getvaloresexamencomponete_spResultDto();

            dto.v_ComponentFieldId = entity.v_ComponentFieldId;
            dto.v_ComponentFielName = entity.v_ComponentFielName;
            dto.v_ServiceComponentFieldsId = entity.v_ServiceComponentFieldsId;
            dto.v_Value1 = entity.v_Value1;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getvaloresexamencomponete_spResultDto"/> to an instance of <see cref="getvaloresexamencomponete_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getvaloresexamencomponete_spResult> ToEntities(this IEnumerable<getvaloresexamencomponete_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getvaloresexamencomponete_spResult"/> to an instance of <see cref="getvaloresexamencomponete_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getvaloresexamencomponete_spResultDto> ToDTOs(this IEnumerable<getvaloresexamencomponete_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
