//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getworkerdata_spResult"/> and <see cref="getworkerdata_spResultDto"/>.
    /// </summary>
    public static partial class getworkerdata_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getworkerdata_spResultDto"/> converted from <see cref="getworkerdata_spResult"/>.</param>
        static partial void OnDTO(this getworkerdata_spResult entity, getworkerdata_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getworkerdata_spResult"/> converted from <see cref="getworkerdata_spResultDto"/>.</param>
        static partial void OnEntity(this getworkerdata_spResultDto dto, getworkerdata_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getworkerdata_spResultDto"/> to an instance of <see cref="getworkerdata_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getworkerdata_spResultDto"/> to convert.</param>
        public static getworkerdata_spResult ToEntity(this getworkerdata_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getworkerdata_spResult();

            entity.Trabajador = dto.Trabajador;
            entity.FechaNacimiento = dto.FechaNacimiento;
            entity.Genero = dto.Genero;
            entity.Puesto = dto.Puesto;
            entity.Protocolo = dto.Protocolo;
            entity.TipoExamen = dto.TipoExamen;
            entity.Grupo = dto.Grupo;
            entity.PersonId = dto.PersonId;
            entity.PersonImage = dto.PersonImage;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getworkerdata_spResult"/> to an instance of <see cref="getworkerdata_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getworkerdata_spResult"/> to convert.</param>
        public static getworkerdata_spResultDto ToDTO(this getworkerdata_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getworkerdata_spResultDto();

            dto.Trabajador = entity.Trabajador;
            dto.FechaNacimiento = entity.FechaNacimiento;
            dto.Genero = entity.Genero;
            dto.Puesto = entity.Puesto;
            dto.Protocolo = entity.Protocolo;
            dto.TipoExamen = entity.TipoExamen;
            dto.Grupo = entity.Grupo;
            dto.PersonId = entity.PersonId;
            dto.PersonImage = entity.PersonImage;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getworkerdata_spResultDto"/> to an instance of <see cref="getworkerdata_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getworkerdata_spResult> ToEntities(this IEnumerable<getworkerdata_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getworkerdata_spResult"/> to an instance of <see cref="getworkerdata_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getworkerdata_spResultDto> ToDTOs(this IEnumerable<getworkerdata_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
