//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="isexistuserResult"/> and <see cref="isexistuserResultDto"/>.
    /// </summary>
    public static partial class isexistuserResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="isexistuserResultDto"/> converted from <see cref="isexistuserResult"/>.</param>
        static partial void OnDTO(this isexistuserResult entity, isexistuserResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="isexistuserResult"/> converted from <see cref="isexistuserResultDto"/>.</param>
        static partial void OnEntity(this isexistuserResultDto dto, isexistuserResult entity);

        /// <summary>
        /// Converts this instance of <see cref="isexistuserResultDto"/> to an instance of <see cref="isexistuserResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="isexistuserResultDto"/> to convert.</param>
        public static isexistuserResult ToEntity(this isexistuserResultDto dto)
        {
            if (dto == null) return null;

            var entity = new isexistuserResult();

            entity.number_of_users = dto.number_of_users;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="isexistuserResult"/> to an instance of <see cref="isexistuserResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="isexistuserResult"/> to convert.</param>
        public static isexistuserResultDto ToDTO(this isexistuserResult entity)
        {
            if (entity == null) return null;

            var dto = new isexistuserResultDto();

            dto.number_of_users = entity.number_of_users;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="isexistuserResultDto"/> to an instance of <see cref="isexistuserResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<isexistuserResult> ToEntities(this IEnumerable<isexistuserResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="isexistuserResult"/> to an instance of <see cref="isexistuserResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<isexistuserResultDto> ToDTOs(this IEnumerable<isexistuserResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
