//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="listmissingexamenesnames_spResult"/> and <see cref="listmissingexamenesnames_spResultDto"/>.
    /// </summary>
    public static partial class listmissingexamenesnames_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="listmissingexamenesnames_spResultDto"/> converted from <see cref="listmissingexamenesnames_spResult"/>.</param>
        static partial void OnDTO(this listmissingexamenesnames_spResult entity, listmissingexamenesnames_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="listmissingexamenesnames_spResult"/> converted from <see cref="listmissingexamenesnames_spResultDto"/>.</param>
        static partial void OnEntity(this listmissingexamenesnames_spResultDto dto, listmissingexamenesnames_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="listmissingexamenesnames_spResultDto"/> to an instance of <see cref="listmissingexamenesnames_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="listmissingexamenesnames_spResultDto"/> to convert.</param>
        public static listmissingexamenesnames_spResult ToEntity(this listmissingexamenesnames_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new listmissingexamenesnames_spResult();

            entity.v_CategoryName = dto.v_CategoryName;
            entity.v_ComponentId = dto.v_ComponentId;
            entity.v_ServiceComponentId = dto.v_ServiceComponentId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="listmissingexamenesnames_spResult"/> to an instance of <see cref="listmissingexamenesnames_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="listmissingexamenesnames_spResult"/> to convert.</param>
        public static listmissingexamenesnames_spResultDto ToDTO(this listmissingexamenesnames_spResult entity)
        {
            if (entity == null) return null;

            var dto = new listmissingexamenesnames_spResultDto();

            dto.v_CategoryName = entity.v_CategoryName;
            dto.v_ComponentId = entity.v_ComponentId;
            dto.v_ServiceComponentId = entity.v_ServiceComponentId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="listmissingexamenesnames_spResultDto"/> to an instance of <see cref="listmissingexamenesnames_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<listmissingexamenesnames_spResult> ToEntities(this IEnumerable<listmissingexamenesnames_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="listmissingexamenesnames_spResult"/> to an instance of <see cref="listmissingexamenesnames_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<listmissingexamenesnames_spResultDto> ToDTOs(this IEnumerable<listmissingexamenesnames_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
