//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:44
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="llenarcomboaltitud_spResult"/> and <see cref="llenarcomboaltitud_spResultDto"/>.
    /// </summary>
    public static partial class llenarcomboaltitud_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="llenarcomboaltitud_spResultDto"/> converted from <see cref="llenarcomboaltitud_spResult"/>.</param>
        static partial void OnDTO(this llenarcomboaltitud_spResult entity, llenarcomboaltitud_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="llenarcomboaltitud_spResult"/> converted from <see cref="llenarcomboaltitud_spResultDto"/>.</param>
        static partial void OnEntity(this llenarcomboaltitud_spResultDto dto, llenarcomboaltitud_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="llenarcomboaltitud_spResultDto"/> to an instance of <see cref="llenarcomboaltitud_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="llenarcomboaltitud_spResultDto"/> to convert.</param>
        public static llenarcomboaltitud_spResult ToEntity(this llenarcomboaltitud_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new llenarcomboaltitud_spResult();

            entity.EsoId = dto.EsoId;
            entity.Nombre = dto.Nombre;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="llenarcomboaltitud_spResult"/> to an instance of <see cref="llenarcomboaltitud_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="llenarcomboaltitud_spResult"/> to convert.</param>
        public static llenarcomboaltitud_spResultDto ToDTO(this llenarcomboaltitud_spResult entity)
        {
            if (entity == null) return null;

            var dto = new llenarcomboaltitud_spResultDto();

            dto.EsoId = entity.EsoId;
            dto.Nombre = entity.Nombre;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="llenarcomboaltitud_spResultDto"/> to an instance of <see cref="llenarcomboaltitud_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<llenarcomboaltitud_spResult> ToEntities(this IEnumerable<llenarcomboaltitud_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="llenarcomboaltitud_spResult"/> to an instance of <see cref="llenarcomboaltitud_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<llenarcomboaltitud_spResultDto> ToDTOs(this IEnumerable<llenarcomboaltitud_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
