//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="llenarcomboprotocolo_spResult"/> and <see cref="llenarcomboprotocolo_spResultDto"/>.
    /// </summary>
    public static partial class llenarcomboprotocolo_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="llenarcomboprotocolo_spResultDto"/> converted from <see cref="llenarcomboprotocolo_spResult"/>.</param>
        static partial void OnDTO(this llenarcomboprotocolo_spResult entity, llenarcomboprotocolo_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="llenarcomboprotocolo_spResult"/> converted from <see cref="llenarcomboprotocolo_spResultDto"/>.</param>
        static partial void OnEntity(this llenarcomboprotocolo_spResultDto dto, llenarcomboprotocolo_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="llenarcomboprotocolo_spResultDto"/> to an instance of <see cref="llenarcomboprotocolo_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="llenarcomboprotocolo_spResultDto"/> to convert.</param>
        public static llenarcomboprotocolo_spResult ToEntity(this llenarcomboprotocolo_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new llenarcomboprotocolo_spResult();

            entity.Id = dto.Id;
            entity.Nombre = dto.Nombre;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="llenarcomboprotocolo_spResult"/> to an instance of <see cref="llenarcomboprotocolo_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="llenarcomboprotocolo_spResult"/> to convert.</param>
        public static llenarcomboprotocolo_spResultDto ToDTO(this llenarcomboprotocolo_spResult entity)
        {
            if (entity == null) return null;

            var dto = new llenarcomboprotocolo_spResultDto();

            dto.Id = entity.Id;
            dto.Nombre = entity.Nombre;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="llenarcomboprotocolo_spResultDto"/> to an instance of <see cref="llenarcomboprotocolo_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<llenarcomboprotocolo_spResult> ToEntities(this IEnumerable<llenarcomboprotocolo_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="llenarcomboprotocolo_spResult"/> to an instance of <see cref="llenarcomboprotocolo_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<llenarcomboprotocolo_spResultDto> ToDTOs(this IEnumerable<llenarcomboprotocolo_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
