//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:36:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="obtenergesoid_spResult"/> and <see cref="obtenergesoid_spResultDto"/>.
    /// </summary>
    public static partial class obtenergesoid_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="obtenergesoid_spResultDto"/> converted from <see cref="obtenergesoid_spResult"/>.</param>
        static partial void OnDTO(this obtenergesoid_spResult entity, obtenergesoid_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="obtenergesoid_spResult"/> converted from <see cref="obtenergesoid_spResultDto"/>.</param>
        static partial void OnEntity(this obtenergesoid_spResultDto dto, obtenergesoid_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="obtenergesoid_spResultDto"/> to an instance of <see cref="obtenergesoid_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="obtenergesoid_spResultDto"/> to convert.</param>
        public static obtenergesoid_spResult ToEntity(this obtenergesoid_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new obtenergesoid_spResult();

            entity.v_GroupOccupationId = dto.v_GroupOccupationId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="obtenergesoid_spResult"/> to an instance of <see cref="obtenergesoid_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="obtenergesoid_spResult"/> to convert.</param>
        public static obtenergesoid_spResultDto ToDTO(this obtenergesoid_spResult entity)
        {
            if (entity == null) return null;

            var dto = new obtenergesoid_spResultDto();

            dto.v_GroupOccupationId = entity.v_GroupOccupationId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenergesoid_spResultDto"/> to an instance of <see cref="obtenergesoid_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<obtenergesoid_spResult> ToEntities(this IEnumerable<obtenergesoid_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenergesoid_spResult"/> to an instance of <see cref="obtenergesoid_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<obtenergesoid_spResultDto> ToDTOs(this IEnumerable<obtenergesoid_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
