//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:35:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="obtenercontactoemergencia_spResult"/> and <see cref="obtenercontactoemergencia_spResultDto"/>.
    /// </summary>
    public static partial class obtenercontactoemergencia_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="obtenercontactoemergencia_spResultDto"/> converted from <see cref="obtenercontactoemergencia_spResult"/>.</param>
        static partial void OnDTO(this obtenercontactoemergencia_spResult entity, obtenercontactoemergencia_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="obtenercontactoemergencia_spResult"/> converted from <see cref="obtenercontactoemergencia_spResultDto"/>.</param>
        static partial void OnEntity(this obtenercontactoemergencia_spResultDto dto, obtenercontactoemergencia_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="obtenercontactoemergencia_spResultDto"/> to an instance of <see cref="obtenercontactoemergencia_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="obtenercontactoemergencia_spResultDto"/> to convert.</param>
        public static obtenercontactoemergencia_spResult ToEntity(this obtenercontactoemergencia_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new obtenercontactoemergencia_spResult();

            entity.ContactoEmergenciaId = dto.ContactoEmergenciaId;
            entity.ContactoEmergencia = dto.ContactoEmergencia;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="obtenercontactoemergencia_spResult"/> to an instance of <see cref="obtenercontactoemergencia_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="obtenercontactoemergencia_spResult"/> to convert.</param>
        public static obtenercontactoemergencia_spResultDto ToDTO(this obtenercontactoemergencia_spResult entity)
        {
            if (entity == null) return null;

            var dto = new obtenercontactoemergencia_spResultDto();

            dto.ContactoEmergenciaId = entity.ContactoEmergenciaId;
            dto.ContactoEmergencia = entity.ContactoEmergencia;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenercontactoemergencia_spResultDto"/> to an instance of <see cref="obtenercontactoemergencia_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<obtenercontactoemergencia_spResult> ToEntities(this IEnumerable<obtenercontactoemergencia_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenercontactoemergencia_spResult"/> to an instance of <see cref="obtenercontactoemergencia_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<obtenercontactoemergencia_spResultDto> ToDTOs(this IEnumerable<obtenercontactoemergencia_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
