//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:36:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="reportematrizshauindo_spResult"/> and <see cref="reportematrizshauindo_spResultDto"/>.
    /// </summary>
    public static partial class reportematrizshauindo_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="reportematrizshauindo_spResultDto"/> converted from <see cref="reportematrizshauindo_spResult"/>.</param>
        static partial void OnDTO(this reportematrizshauindo_spResult entity, reportematrizshauindo_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="reportematrizshauindo_spResult"/> converted from <see cref="reportematrizshauindo_spResultDto"/>.</param>
        static partial void OnEntity(this reportematrizshauindo_spResultDto dto, reportematrizshauindo_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="reportematrizshauindo_spResultDto"/> to an instance of <see cref="reportematrizshauindo_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="reportematrizshauindo_spResultDto"/> to convert.</param>
        public static reportematrizshauindo_spResult ToEntity(this reportematrizshauindo_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new reportematrizshauindo_spResult();

            entity.ServiceId = dto.ServiceId;
            entity.PersonId = dto.PersonId;
            entity.ProtocolId = dto.ProtocolId;
            entity.Protocolo = dto.Protocolo;
            entity.v_CustomerOrganizationId = dto.v_CustomerOrganizationId;
            entity.P_EmployerOrganizationId = dto.P_EmployerOrganizationId;
            entity.v_WorkingOrganizationId = dto.v_WorkingOrganizationId;
            entity.v_CustomerLocationId = dto.v_CustomerLocationId;
            entity.v_WorkingLocationId = dto.v_WorkingLocationId;
            entity.v_EmployerLocationId = dto.v_EmployerLocationId;
            entity.TipoEmo = dto.TipoEmo;
            entity.DniPasaporte = dto.DniPasaporte;
            entity.FechaExamen = dto.FechaExamen;
            entity.ApellidosNombres = dto.ApellidosNombres;
            entity.FechaNacimiento = dto.FechaNacimiento;
            entity.TelefonoContacto = dto.TelefonoContacto;
            entity.P_Sexo = dto.P_Sexo;
            entity.EstadoCivil = dto.EstadoCivil;
            entity.GradoInstruccion = dto.GradoInstruccion;
            entity.P_Grupo = dto.P_Grupo;
            entity.P_Factor = dto.P_Factor;
            entity.Ocupacion = dto.Ocupacion;
            entity.General = dto.General;
            entity.Contrata = dto.Contrata;
            entity.Subcontrata = dto.Subcontrata;
            entity.Unida = dto.Unida;
            entity.P_AptitudFinal = dto.P_AptitudFinal;
            entity.P_VigenciaEmo = dto.P_VigenciaEmo;
            entity.Area = dto.Area;
            entity.Procedencia = dto.Procedencia;
            entity.NumeroHijos = dto.NumeroHijos;
            entity.edad = dto.edad;
            entity.Sintomas = dto.Sintomas;
            entity.Facturacion = dto.Facturacion;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="reportematrizshauindo_spResult"/> to an instance of <see cref="reportematrizshauindo_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="reportematrizshauindo_spResult"/> to convert.</param>
        public static reportematrizshauindo_spResultDto ToDTO(this reportematrizshauindo_spResult entity)
        {
            if (entity == null) return null;

            var dto = new reportematrizshauindo_spResultDto();

            dto.ServiceId = entity.ServiceId;
            dto.PersonId = entity.PersonId;
            dto.ProtocolId = entity.ProtocolId;
            dto.Protocolo = entity.Protocolo;
            dto.v_CustomerOrganizationId = entity.v_CustomerOrganizationId;
            dto.P_EmployerOrganizationId = entity.P_EmployerOrganizationId;
            dto.v_WorkingOrganizationId = entity.v_WorkingOrganizationId;
            dto.v_CustomerLocationId = entity.v_CustomerLocationId;
            dto.v_WorkingLocationId = entity.v_WorkingLocationId;
            dto.v_EmployerLocationId = entity.v_EmployerLocationId;
            dto.TipoEmo = entity.TipoEmo;
            dto.DniPasaporte = entity.DniPasaporte;
            dto.FechaExamen = entity.FechaExamen;
            dto.ApellidosNombres = entity.ApellidosNombres;
            dto.FechaNacimiento = entity.FechaNacimiento;
            dto.TelefonoContacto = entity.TelefonoContacto;
            dto.P_Sexo = entity.P_Sexo;
            dto.EstadoCivil = entity.EstadoCivil;
            dto.GradoInstruccion = entity.GradoInstruccion;
            dto.P_Grupo = entity.P_Grupo;
            dto.P_Factor = entity.P_Factor;
            dto.Ocupacion = entity.Ocupacion;
            dto.General = entity.General;
            dto.Contrata = entity.Contrata;
            dto.Subcontrata = entity.Subcontrata;
            dto.Unida = entity.Unida;
            dto.P_AptitudFinal = entity.P_AptitudFinal;
            dto.P_VigenciaEmo = entity.P_VigenciaEmo;
            dto.Area = entity.Area;
            dto.Procedencia = entity.Procedencia;
            dto.NumeroHijos = entity.NumeroHijos;
            dto.edad = entity.edad;
            dto.Sintomas = entity.Sintomas;
            dto.Facturacion = entity.Facturacion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="reportematrizshauindo_spResultDto"/> to an instance of <see cref="reportematrizshauindo_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<reportematrizshauindo_spResult> ToEntities(this IEnumerable<reportematrizshauindo_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="reportematrizshauindo_spResult"/> to an instance of <see cref="reportematrizshauindo_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<reportematrizshauindo_spResultDto> ToDTOs(this IEnumerable<reportematrizshauindo_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
