//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2026/08/30 - 00:01:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="riesgos"/> and <see cref="riesgosDto"/>.
    /// </summary>
    public static partial class riesgosAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="riesgosDto"/> converted from <see cref="riesgos"/>.</param>
        static partial void OnDTO(this riesgos entity, riesgosDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="riesgos"/> converted from <see cref="riesgosDto"/>.</param>
        static partial void OnEntity(this riesgosDto dto, riesgos entity);

        /// <summary>
        /// Converts this instance of <see cref="riesgosDto"/> to an instance of <see cref="riesgos"/>.
        /// </summary>
        /// <param name="dto"><see cref="riesgosDto"/> to convert.</param>
        public static riesgos ToEntity(this riesgosDto dto)
        {
            if (dto == null) return null;

            var entity = new riesgos();

            entity.v_RiesgoId = dto.v_RiesgoId;
            entity.v_ServicioId = dto.v_ServicioId;
            entity.b_Ruido = dto.b_Ruido;
            entity.b_Polvo = dto.b_Polvo;
            entity.b_VidaSedentaria = dto.b_VidaSedentaria;
            entity.b_VibTotal = dto.b_VibTotal;
            entity.b_Cancerigenos = dto.b_Cancerigenos;
            entity.b_Mutagenicos = dto.b_Mutagenicos;
            entity.b_Solventes = dto.b_Solventes;
            entity.b_MetalPesado = dto.b_MetalPesado;
            entity.b_Temperatura = dto.b_Temperatura;
            entity.b_Biologicos = dto.b_Biologicos;
            entity.b_Posturas = dto.b_Posturas;
            entity.b_Turnos = dto.b_Turnos;
            entity.b_Cargas = dto.b_Cargas;
            entity.b_MovimientosRepetitivos = dto.b_MovimientosRepetitivos;
            entity.b_PantallaPVD = dto.b_PantallaPVD;
            entity.b_Otros = dto.b_Otros;
            entity.i_Descripcion = dto.i_Descripcion;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="riesgos"/> to an instance of <see cref="riesgosDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="riesgos"/> to convert.</param>
        public static riesgosDto ToDTO(this riesgos entity)
        {
            if (entity == null) return null;

            var dto = new riesgosDto();

            dto.v_RiesgoId = entity.v_RiesgoId;
            dto.v_ServicioId = entity.v_ServicioId;
            dto.b_Ruido = entity.b_Ruido;
            dto.b_Polvo = entity.b_Polvo;
            dto.b_VidaSedentaria = entity.b_VidaSedentaria;
            dto.b_VibTotal = entity.b_VibTotal;
            dto.b_Cancerigenos = entity.b_Cancerigenos;
            dto.b_Mutagenicos = entity.b_Mutagenicos;
            dto.b_Solventes = entity.b_Solventes;
            dto.b_MetalPesado = entity.b_MetalPesado;
            dto.b_Temperatura = entity.b_Temperatura;
            dto.b_Biologicos = entity.b_Biologicos;
            dto.b_Posturas = entity.b_Posturas;
            dto.b_Turnos = entity.b_Turnos;
            dto.b_Cargas = entity.b_Cargas;
            dto.b_MovimientosRepetitivos = entity.b_MovimientosRepetitivos;
            dto.b_PantallaPVD = entity.b_PantallaPVD;
            dto.b_Otros = entity.b_Otros;
            dto.i_Descripcion = entity.i_Descripcion;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="riesgosDto"/> to an instance of <see cref="riesgos"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<riesgos> ToEntities(this IEnumerable<riesgosDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="riesgos"/> to an instance of <see cref="riesgosDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<riesgosDto> ToDTOs(this IEnumerable<riesgos> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
