//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2026/08/29 - 23:58:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="sp_getdatahierarchyResult"/> and <see cref="sp_getdatahierarchyResultDto"/>.
    /// </summary>
    public static partial class sp_getdatahierarchyResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="sp_getdatahierarchyResultDto"/> converted from <see cref="sp_getdatahierarchyResult"/>.</param>
        static partial void OnDTO(this sp_getdatahierarchyResult entity, sp_getdatahierarchyResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="sp_getdatahierarchyResult"/> converted from <see cref="sp_getdatahierarchyResultDto"/>.</param>
        static partial void OnEntity(this sp_getdatahierarchyResultDto dto, sp_getdatahierarchyResult entity);

        /// <summary>
        /// Converts this instance of <see cref="sp_getdatahierarchyResultDto"/> to an instance of <see cref="sp_getdatahierarchyResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="sp_getdatahierarchyResultDto"/> to convert.</param>
        public static sp_getdatahierarchyResult ToEntity(this sp_getdatahierarchyResultDto dto)
        {
            if (dto == null) return null;

            var entity = new sp_getdatahierarchyResult();

            entity.GrupoId = dto.GrupoId;
            entity.ParameterId = dto.ParameterId;
            entity.Value1 = dto.Value1;
            entity.Value2 = dto.Value2;
            entity.Field = dto.Field;
            entity.ParentId = dto.ParentId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="sp_getdatahierarchyResult"/> to an instance of <see cref="sp_getdatahierarchyResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="sp_getdatahierarchyResult"/> to convert.</param>
        public static sp_getdatahierarchyResultDto ToDTO(this sp_getdatahierarchyResult entity)
        {
            if (entity == null) return null;

            var dto = new sp_getdatahierarchyResultDto();

            dto.GrupoId = entity.GrupoId;
            dto.ParameterId = entity.ParameterId;
            dto.Value1 = entity.Value1;
            dto.Value2 = entity.Value2;
            dto.Field = entity.Field;
            dto.ParentId = entity.ParentId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="sp_getdatahierarchyResultDto"/> to an instance of <see cref="sp_getdatahierarchyResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<sp_getdatahierarchyResult> ToEntities(this IEnumerable<sp_getdatahierarchyResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="sp_getdatahierarchyResult"/> to an instance of <see cref="sp_getdatahierarchyResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<sp_getdatahierarchyResultDto> ToDTOs(this IEnumerable<sp_getdatahierarchyResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
