//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2023/03/31 - 10:41:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="variablesentorno_resultadosclinicosweb"/> and <see cref="variablesentorno_resultadosclinicoswebDto"/>.
    /// </summary>
    public static partial class variablesentorno_resultadosclinicoswebAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="variablesentorno_resultadosclinicoswebDto"/> converted from <see cref="variablesentorno_resultadosclinicosweb"/>.</param>
        static partial void OnDTO(this variablesentorno_resultadosclinicosweb entity, variablesentorno_resultadosclinicoswebDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="variablesentorno_resultadosclinicosweb"/> converted from <see cref="variablesentorno_resultadosclinicoswebDto"/>.</param>
        static partial void OnEntity(this variablesentorno_resultadosclinicoswebDto dto, variablesentorno_resultadosclinicosweb entity);

        /// <summary>
        /// Converts this instance of <see cref="variablesentorno_resultadosclinicoswebDto"/> to an instance of <see cref="variablesentorno_resultadosclinicosweb"/>.
        /// </summary>
        /// <param name="dto"><see cref="variablesentorno_resultadosclinicoswebDto"/> to convert.</param>
        public static variablesentorno_resultadosclinicosweb ToEntity(this variablesentorno_resultadosclinicoswebDto dto)
        {
            if (dto == null) return null;

            var entity = new variablesentorno_resultadosclinicosweb();

            entity.i_VariableId = dto.i_VariableId;
            entity.v_NameKey = dto.v_NameKey;
            entity.v_Value = dto.v_Value;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="variablesentorno_resultadosclinicosweb"/> to an instance of <see cref="variablesentorno_resultadosclinicoswebDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="variablesentorno_resultadosclinicosweb"/> to convert.</param>
        public static variablesentorno_resultadosclinicoswebDto ToDTO(this variablesentorno_resultadosclinicosweb entity)
        {
            if (entity == null) return null;

            var dto = new variablesentorno_resultadosclinicoswebDto();

            dto.i_VariableId = entity.i_VariableId;
            dto.v_NameKey = entity.v_NameKey;
            dto.v_Value = entity.v_Value;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="variablesentorno_resultadosclinicoswebDto"/> to an instance of <see cref="variablesentorno_resultadosclinicosweb"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<variablesentorno_resultadosclinicosweb> ToEntities(this IEnumerable<variablesentorno_resultadosclinicoswebDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="variablesentorno_resultadosclinicosweb"/> to an instance of <see cref="variablesentorno_resultadosclinicoswebDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<variablesentorno_resultadosclinicoswebDto> ToDTOs(this IEnumerable<variablesentorno_resultadosclinicosweb> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
